// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class AccountTransactionAndBundle
    {
        public long AccountTransactionId { get; set; }
        public long BundleId { get; set; }

        public virtual AccountTransaction AccountTransaction { get; set; }
        public virtual Bundle Bundle { get; set; }
    }
}