// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Album
    {
        public Album()
        {
            Song = new HashSet<Song>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long? ArtistId { get; set; }

        public virtual Artist Artist { get; set; }
        public virtual ICollection<Song> Song { get; set; }
    }
}