// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Artist
    {
        public Artist()
        {
            Album = new HashSet<Album>();
            Score = new HashSet<Score>();
            Song = new HashSet<Song>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Album> Album { get; set; }
        public virtual ICollection<Score> Score { get; set; }
        public virtual ICollection<Song> Song { get; set; }
    }
}