// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Autoclip
    {
        public Autoclip()
        {
            AccountTransactionAndAutoclip = new HashSet<AccountTransactionAndAutoclip>();
            BundleAndAutoclip = new HashSet<BundleAndAutoclip>();
            DeviceTypeAndAutoclip = new HashSet<DeviceTypeAndAutoclip>();
            Event = new HashSet<Event>();
            GroupAndAutoclip = new HashSet<GroupAndAutoclip>();
            LevelTemplateAndAutoclip = new HashSet<LevelTemplateAndAutoclip>();
            PriceruleAndAutoclip = new HashSet<PriceruleAndAutoclip>();
            QaComments = new HashSet<QaComments>();
            SeasonAndAutoclip = new HashSet<SeasonAndAutoclip>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long GroupId { get; set; }
        public long AutoClipCategoryId { get; set; }
        public long? Size { get; set; }
        public long ReadinessId { get; set; }
        public long UploaderUserId { get; set; }

        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual AutoclipCategory AutoClipCategory { get; set; }
        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual ICollection<AccountTransactionAndAutoclip> AccountTransactionAndAutoclip { get; set; }
        public virtual ICollection<BundleAndAutoclip> BundleAndAutoclip { get; set; }
        public virtual ICollection<DeviceTypeAndAutoclip> DeviceTypeAndAutoclip { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<GroupAndAutoclip> GroupAndAutoclip { get; set; }
        public virtual ICollection<LevelTemplateAndAutoclip> LevelTemplateAndAutoclip { get; set; }
        public virtual ICollection<PriceruleAndAutoclip> PriceruleAndAutoclip { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
        public virtual ICollection<SeasonAndAutoclip> SeasonAndAutoclip { get; set; }
    }
}