// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BodyAnimation
    {
        public BodyAnimation()
        {
            AccountTransactionAndBodyAnimation = new HashSet<AccountTransactionAndBodyAnimation>();
            BodyAnimationAndBodyAnimationCategory = new HashSet<BodyAnimationAndBodyAnimationCategory>();
            BodyAnimationAndCharacterSpawnPosition = new HashSet<BodyAnimationAndCharacterSpawnPosition>();
            BodyAnimationAndSong = new HashSet<BodyAnimationAndSong>();
            BundleAndBodyAnimation = new HashSet<BundleAndBodyAnimation>();
            CharacterControllerBackgroundDancerLowerBodyAnimation = new HashSet<CharacterControllerBackgroundDancer>();
            CharacterControllerBackgroundDancerPrimaryBodyAnimation = new HashSet<CharacterControllerBackgroundDancer>();
            CharacterControllerBodyAnimationLowerBodyAnimation = new HashSet<CharacterControllerBodyAnimation>();
            CharacterControllerBodyAnimationPrimaryBodyAnimation = new HashSet<CharacterControllerBodyAnimation>();
            DeviceTypeAndBodyAnimation = new HashSet<DeviceTypeAndBodyAnimation>();
            GroupAndBodyAnimation = new HashSet<GroupAndBodyAnimation>();
            LevelTemplateAndBodyAnimation = new HashSet<LevelTemplateAndBodyAnimation>();
            PriceruleAndBodyAnimation = new HashSet<PriceruleAndBodyAnimation>();
            PropAndBodyAnimation = new HashSet<PropAndBodyAnimation>();
            PropController = new HashSet<PropController>();
            QaComments = new HashSet<QaComments>();
            SeasonAndBodyAnimation = new HashSet<SeasonAndBodyAnimation>();
            WardrobeAndBodyAnimation = new HashSet<WardrobeAndBodyAnimation>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long AnimationDirectionId { get; set; }
        public long GroupId { get; set; }
        public long ReadinessId { get; set; }
        public bool Locomotion { get; set; }
        public bool Looping { get; set; }
        public bool Continous { get; set; }
        public bool Splittable { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long SizeKb { get; set; }
        public int? Duration { get; set; }
        public int? FrameRate { get; set; }
        public string Name { get; set; }
        public long BodyAnimationCategoryId { get; set; }
        public long UploaderUserId { get; set; }
        public bool IsDefault { get; set; }
        public bool IsStartPackMember { get; set; }
        public long? BodyAnimationSpaceSizeId { get; set; }
        public long[] Tags { get; set; }
        public string FilesInfo { get; set; }
        public int SortOrder { get; set; }
        public int ThumbnailCharacter { get; set; }
        public bool HasFaceAnimation { get; set; }
        public long? AssetTierId { get; set; }
        public long? MovementTypeId { get; set; }
        public long? BodyAnimationGroupId { get; set; }
        public int? OrderIndexInGroup { get; set; }

        public virtual AssetTier AssetTier { get; set; }
        public virtual AnimationDirection AnimationDirection { get; set; }
        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual BodyAnimationCategory BodyAnimationCategory { get; set; }
        public virtual BodyAnimationSpaceSize BodyAnimationSpaceSize { get; set; }
        public virtual ICollection<CharacterSpawnPosition> CharacterSpawnPosition { get; set; }
        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual MovementType MovementType { get; set; }
        public virtual ICollection<AccountTransactionAndBodyAnimation> AccountTransactionAndBodyAnimation { get; set; }
        public virtual ICollection<BodyAnimationAndBodyAnimationCategory> BodyAnimationAndBodyAnimationCategory { get; set; }
        public virtual ICollection<BodyAnimationAndCharacterSpawnPosition> BodyAnimationAndCharacterSpawnPosition { get; set; }
        public virtual ICollection<BodyAnimationAndSong> BodyAnimationAndSong { get; set; }
        public virtual ICollection<BundleAndBodyAnimation> BundleAndBodyAnimation { get; set; }
        public virtual ICollection<CharacterControllerBackgroundDancer> CharacterControllerBackgroundDancerLowerBodyAnimation { get; set; }
        public virtual ICollection<CharacterControllerBackgroundDancer> CharacterControllerBackgroundDancerPrimaryBodyAnimation { get; set; }
        public virtual ICollection<CharacterControllerBodyAnimation> CharacterControllerBodyAnimationLowerBodyAnimation { get; set; }
        public virtual ICollection<CharacterControllerBodyAnimation> CharacterControllerBodyAnimationPrimaryBodyAnimation { get; set; }
        public virtual ICollection<DeviceTypeAndBodyAnimation> DeviceTypeAndBodyAnimation { get; set; }
        public virtual ICollection<GroupAndBodyAnimation> GroupAndBodyAnimation { get; set; }
        public virtual ICollection<LevelTemplateAndBodyAnimation> LevelTemplateAndBodyAnimation { get; set; }
        public virtual ICollection<PriceruleAndBodyAnimation> PriceruleAndBodyAnimation { get; set; }
        public virtual ICollection<PropAndBodyAnimation> PropAndBodyAnimation { get; set; }
        public virtual ICollection<PropController> PropController { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
        public virtual ICollection<SeasonAndBodyAnimation> SeasonAndBodyAnimation { get; set; }
        public virtual ICollection<WardrobeAndBodyAnimation> WardrobeAndBodyAnimation { get; set; }
    }
}