// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BodyAnimationCategoryAndGenre
    {
        public long BodyAnimationCategoryId { get; set; }
        public long GenreId { get; set; }

        public virtual BodyAnimationCategory BodyAnimationCategory { get; set; }
        public virtual Genre Genre { get; set; }
    }
}