// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BrandAndCameraFilterCategory
    {
        public long BrandId { get; set; }
        public long CameraFilterCategoryId { get; set; }
        public int BrandSortKey { get; set; }
        public int CameraFilterCategorySortKey { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual CameraFilterCategory CameraFilterCategory { get; set; }
    }
}