// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BrandAndSetLocationCategory
    {
        public long BrandId { get; set; }
        public long SetLocationCategoryId { get; set; }
        public int BrandSortKey { get; set; }
        public int SetLocationCategorySortKey { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual SetLocationCategory SetLocationCategory { get; set; }
    }
}