// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Brand
    {
        public Brand()
        {
            BrandAndCameraFilterCategory = new HashSet<BrandAndCameraFilterCategory>();
            BrandAndGenre = new HashSet<BrandAndGenre>();
            BrandAndPropCategory = new HashSet<BrandAndPropCategory>();
            BrandAndScoreCategory = new HashSet<BrandAndScoreCategory>();
            BrandAndSetLocationCategory = new HashSet<BrandAndSetLocationCategory>();
            BrandAndSetLocationMood = new HashSet<BrandAndSetLocationMood>();
            BrandAndSfxCategory = new HashSet<BrandAndSfxCategory>();
            BrandAndVfxCategory = new HashSet<BrandAndVfxCategory>();
            Prop = new HashSet<Prop>();
            Sticker = new HashSet<Sticker>();
            Wardrobe = new HashSet<Wardrobe>();
            WardrobeCollection = new HashSet<WardrobeCollection>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public string Name { get; set; }

        public virtual Group Group { get; set; }
        public virtual ICollection<BrandAndCameraFilterCategory> BrandAndCameraFilterCategory { get; set; }
        public virtual ICollection<BrandAndGenre> BrandAndGenre { get; set; }
        public virtual ICollection<BrandAndPropCategory> BrandAndPropCategory { get; set; }
        public virtual ICollection<BrandAndScoreCategory> BrandAndScoreCategory { get; set; }
        public virtual ICollection<BrandAndSetLocationCategory> BrandAndSetLocationCategory { get; set; }
        public virtual ICollection<BrandAndSetLocationMood> BrandAndSetLocationMood { get; set; }
        public virtual ICollection<BrandAndSfxCategory> BrandAndSfxCategory { get; set; }
        public virtual ICollection<BrandAndVfxCategory> BrandAndVfxCategory { get; set; }
        public virtual ICollection<Prop> Prop { get; set; }
        public virtual ICollection<Sticker> Sticker { get; set; }
        public virtual ICollection<Wardrobe> Wardrobe { get; set; }
        public virtual ICollection<WardrobeCollection> WardrobeCollection { get; set; }
    }
}