// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BrandAndPropCategory
    {
        public long BrandId { get; set; }
        public long PropCategoryId { get; set; }
        public int BrandSortKey { get; set; }
        public int PropCategorySortKey { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual PropCategory PropCategory { get; set; }
    }
}