// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BrandAndSfxCategory
    {
        public long BrandId { get; set; }
        public long SfxCategoryId { get; set; }
        public int BrandSortKey { get; set; }
        public int SfxCategorySortKey { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual SfxCategory SfxCategory { get; set; }
    }
}