// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BundleAndProp
    {
        public long BundleId { get; set; }
        public long PropId { get; set; }

        public virtual Bundle Bundle { get; set; }
        public virtual Prop Prop { get; set; }
    }
}