// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BundleAndVoiceFilter
    {
        public long BundleId { get; set; }
        public long VoiceFilterId { get; set; }

        public virtual Bundle Bundle { get; set; }
        public virtual VoiceFilter VoiceFilter { get; set; }
    }
}