// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CameraAnimationType
    {
        public CameraAnimationType()
        {
            CameraAnimationTemplate = new HashSet<CameraAnimationTemplate>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long GroupId { get; set; }
        public string FilesInfo { get; set; }

        public virtual Group Group { get; set; }
        public virtual ICollection<CameraAnimationTemplate> CameraAnimationTemplate { get; set; }
    }
}