// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CameraFilterController
    {
        public long Id { get; set; }
        public long EventId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public long CameraFilterVariantId { get; set; }
        public int? CameraFilterValue { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }
        public int StackNumber { get; set; }

        public virtual CameraFilterVariant CameraFilterVariant { get; set; }
        public virtual Event Event { get; set; }
    }
}