// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CameraController
    {
        public long Id { get; set; }
        public long EventId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }
        public long CameraAnimationTemplateId { get; set; }
        public int SpawnIndex { get; set; }
        public int StartDepthOfFieldOffset { get; set; }
        public int EndDepthOfFieldOffset { get; set; }
        public int StartFocusDistance { get; set; }
        public int EndFocusDistance { get; set; }
        public int? FollowSpawnPositionIndex { get; set; }
        public bool FollowAll { get; set; }
        public int? LookAtIndex { get; set; }
        public int CameraNoiseSettingsIndex { get; set; }
        public bool AutoFocus { get; set; }
        public bool AutoRoll { get; set; }
        public bool FollowZoom { get; set; }
        public long? CameraAnimationId { get; set; }
        public int TemplateSpeed { get; set; }

        public virtual CameraAnimation CameraAnimation { get; set; }
        public virtual CameraAnimationTemplate CameraAnimationTemplate { get; set; }
        public virtual Event Event { get; set; }
    }
}