// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CampaignAndDeviceType
    {
        public long CampaignId { get; set; }
        public long DeviceTypeId { get; set; }

        public virtual Campaign Campaign { get; set; }
        public virtual DeviceType DeviceType { get; set; }
    }
}