// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Bridge.Models.AsseManager
{
    public partial class Campaign
    {
        public Campaign()
        {
            CampaignAndDeviceType = new HashSet<CampaignAndDeviceType>();
            CampaignAndGroup = new HashSet<CampaignAndGroup>();
            CampaignAndTeam = new HashSet<CampaignAndTeam>();
            CampaignAndUser = new HashSet<CampaignAndUser>();
            CampaignAndVerticalCategory = new HashSet<CampaignAndVerticalCategory>();
            CampaignFulfillment = new HashSet<CampaignFulfillment>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public long CampaignTypeId { get; set; }
        public long ImplementationTypeId { get; set; }
        public string Name { get; set; }
        public int? MaxCount { get; set; }
        public DateTime ValidDuring { get; set; }
        public int RewardAmount { get; set; }
        public long? RewardBadgeId { get; set; }
        public string Rules { get; set; }

        public virtual CampaignType CampaignType { get; set; }
        public virtual Group Group { get; set; }
        public virtual CampaignImplementationType ImplementationType { get; set; }
        public virtual Badge RewardBadge { get; set; }
        public virtual ICollection<CampaignAndDeviceType> CampaignAndDeviceType { get; set; }
        public virtual ICollection<CampaignAndGroup> CampaignAndGroup { get; set; }
        public virtual ICollection<CampaignAndTeam> CampaignAndTeam { get; set; }
        public virtual ICollection<CampaignAndUser> CampaignAndUser { get; set; }
        public virtual ICollection<CampaignAndVerticalCategory> CampaignAndVerticalCategory { get; set; }
        public virtual ICollection<CampaignFulfillment> CampaignFulfillment { get; set; }
    }
}