// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CharacterSpawnPosition
    {
        public CharacterSpawnPosition()
        {
            BodyAnimationAndCharacterSpawnPosition = new HashSet<BodyAnimationAndCharacterSpawnPosition>();
            CharacterSpawnPositionAndFormation = new HashSet<CharacterSpawnPositionAndFormation>();
            Event = new HashSet<Event>();
            LightSettings = new HashSet<LightSettings>();
            SetLocationAndCharacterSpawnPosition = new HashSet<SetLocationAndCharacterSpawnPosition>();
        }

        public long Id { get; set; }
        public Guid UnityGuid { get; set; }
        public long SetLocationBundleId { get; set; }
        public string Name { get; set; }
        public long GroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long SpawnPositionSpaceSizeId { get; set; }
        public bool Moving { get; set; }
        public int MaxCharactersAmount { get; set; }
        public int DefaultDayTime { get; set; }
        public long BodyAnimationSpaceSizeId { get; set; }
        public string FilesInfo { get; set; }
        public bool IsDefault { get; set; }
        public long[] Tags { get; set; }
        public float[] Position { get; set; }
        public float[] Rotation { get; set; }
        public long? MovementTypeId { get; set; }
        public bool AvailableForSelection { get; set; }
        public int? SpawnPositionGroupId { get; set; }
        public int? SpawnOrderIndex { get; set; }
        public long? DefaultBodyAnimationId { get; set; }

        public virtual BodyAnimationSpaceSize BodyAnimationSpaceSize { get; set; }
        public virtual Group Group { get; set; }
        public virtual SetLocationBundle SetLocationBundle { get; set; }
        public virtual SpawnPositionSpaceSize SpawnPositionSpaceSize { get; set; }
        public virtual MovementType MovementType { get; set; }
        public virtual BodyAnimation DefaultBodyAnimation { get; set; }
        public virtual ICollection<BodyAnimationAndCharacterSpawnPosition> BodyAnimationAndCharacterSpawnPosition { get; set; }
        public virtual ICollection<CharacterSpawnPositionAndFormation> CharacterSpawnPositionAndFormation { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<LightSettings> LightSettings { get; set; }
        public virtual ICollection<SetLocationAndCharacterSpawnPosition> SetLocationAndCharacterSpawnPosition { get; set; }
    }
}