// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CharacterController
    {
        public CharacterController()
        {
            CharacterControllerBackgroundDancer = new HashSet<CharacterControllerBackgroundDancer>();
            CharacterControllerBodyAnimation = new HashSet<CharacterControllerBodyAnimation>();
            CharacterControllerFaceVoice = new HashSet<CharacterControllerFaceVoice>();
            CharacterControllerUmaRecipe = new HashSet<CharacterControllerUmaRecipe>();
        }

        public long Id { get; set; }
        public long EventId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public long CharacterId { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }
        public int Rotation { get; set; }
        public long? OutfitId { get; set; }

        public virtual Character Character { get; set; }
        public virtual Event Event { get; set; }
        public virtual Outfit Outfit { get; set; }

        public virtual ICollection<CharacterControllerBackgroundDancer> CharacterControllerBackgroundDancer { get; set; }
        public virtual ICollection<CharacterControllerBodyAnimation> CharacterControllerBodyAnimation { get; set; }
        public virtual ICollection<CharacterControllerFaceVoice> CharacterControllerFaceVoice { get; set; }
        public virtual ICollection<CharacterControllerUmaRecipe> CharacterControllerUmaRecipe { get; set; }
    }
}