// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CharacterControllerBodyAnimation
    {
        public long Id { get; set; }
        public long CharacterControllerId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public long PrimaryBodyAnimationId { get; set; }
        public long? LowerBodyAnimationId { get; set; }
        public int AnimationSpeed { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }
        public bool Locomotion { get; set; }
        public bool Looping { get; set; }

        public virtual CharacterController CharacterController { get; set; }
        public virtual AsseManager.BodyAnimation LowerBodyAnimation { get; set; }
        public virtual AsseManager.BodyAnimation PrimaryBodyAnimation { get; set; }
    }
}