// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CharacterSpawnPositionAndFormation
    {
        public long CharacterSpawnPositionFormationId { get; set; }
        public long CharacterSpawnPositionId { get; set; }

        public virtual CharacterSpawnPosition CharacterSpawnPosition { get; set; }
        public virtual CharacterSpawnPositionFormation CharacterSpawnPositionFormation { get; set; }
    }
}