// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CharacterGroupPermission
    {
        public long CharacterId { get; set; }
        public long GroupId { get; set; }

        public virtual Character Character { get; set; }
        public virtual Group Group { get; set; }
    }
}