// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Bridge.ExternalPackages.Protobuf;

namespace Bridge.Models.AsseManager
{
    public partial class Character
    {
        public Character()
        {
            AccountTransactionAndCharacter = new HashSet<AccountTransactionAndCharacter>();
            BundleAndCharacter = new HashSet<BundleAndCharacter>();
            CharacterAndUmaRecipe = new HashSet<CharacterAndUmaRecipe>();
            CharacterController = new HashSet<CharacterController>();
            CharacterControllerBackgroundDancer = new HashSet<CharacterControllerBackgroundDancer>();
            CharacterGroupPermission = new HashSet<CharacterGroupPermission>();
            CharacterTeamPermission = new HashSet<CharacterTeamPermission>();
            DeviceTypeAndCharacter = new HashSet<DeviceTypeAndCharacter>();
            GroupAndCharacter = new HashSet<GroupAndCharacter>();
            PriceruleAndCharacter = new HashSet<PriceruleAndCharacter>();
            QaComments = new HashSet<QaComments>();
            SeasonAndCharacter = new HashSet<SeasonAndCharacter>();
            User = new HashSet<User>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long GenderId { get; set; }
        public long CharacterStyleId { get; set; }
        public long GroupId { get; set; }
        public long ReadinessId { get; set; }
        public bool PublicForCreation { get; set; }
        public bool PublicForBackgroundDancing { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long? Size { get; set; }
        public int? PolyCount { get; set; }
        public long UploaderUserId { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public long DefaultOutfitId { get; set; }
        public bool IsDefault { get; set; }
        public string FilesInfo { get; set; }
        public int SortOrder { get; set; }

        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual CharacterStyle CharacterStyle { get; set; }
        public virtual Outfit DefaultOutfit { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual ICollection<AccountTransactionAndCharacter> AccountTransactionAndCharacter { get; set; }
        public virtual ICollection<BundleAndCharacter> BundleAndCharacter { get; set; }
        public virtual ICollection<CharacterAndUmaRecipe> CharacterAndUmaRecipe { get; set; }
        public virtual ICollection<CharacterController> CharacterController { get; set; }
        public virtual ICollection<CharacterControllerBackgroundDancer> CharacterControllerBackgroundDancer { get; set; }
        public virtual ICollection<CharacterGroupPermission> CharacterGroupPermission { get; set; }
        public virtual ICollection<CharacterTeamPermission> CharacterTeamPermission { get; set; }
        public virtual ICollection<DeviceTypeAndCharacter> DeviceTypeAndCharacter { get; set; }
        public virtual ICollection<GroupAndCharacter> GroupAndCharacter { get; set; }
        public virtual ICollection<PriceruleAndCharacter> PriceruleAndCharacter { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
        public virtual ICollection<SeasonAndCharacter> SeasonAndCharacter { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}