// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Crowd
    {
        public Crowd()
        {
            SetLocationController = new HashSet<SetLocationController>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public long UploaderUserId { get; set; }
        public long CrowdCategoryId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public string DisplayName { get; set; }

        public virtual CrowdCategory CrowdCategory { get; set; }
        public virtual Group Group { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual ICollection<SetLocationController> SetLocationController { get; set; }
    }
}