// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class DeviceType
    {
        public DeviceType()
        {
            CampaignAndDeviceType = new HashSet<CampaignAndDeviceType>();
            DeviceTypeAndAutoclip = new HashSet<DeviceTypeAndAutoclip>();
            DeviceTypeAndBodyAnimation = new HashSet<DeviceTypeAndBodyAnimation>();
            DeviceTypeAndCameraFilter = new HashSet<DeviceTypeAndCameraFilter>();
            DeviceTypeAndCharacter = new HashSet<DeviceTypeAndCharacter>();
            DeviceTypeAndPipeline = new HashSet<DeviceTypeAndPipeline>();
            DeviceTypeAndProp = new HashSet<DeviceTypeAndProp>();
            DeviceTypeAndScore = new HashSet<DeviceTypeAndScore>();
            DeviceTypeAndSetLocation = new HashSet<DeviceTypeAndSetLocation>();
            DeviceTypeAndSong = new HashSet<DeviceTypeAndSong>();
            DeviceTypeAndSticker = new HashSet<DeviceTypeAndSticker>();
            DeviceTypeAndVfx = new HashSet<DeviceTypeAndVfx>();
            DeviceTypeAndVoiceFilter = new HashSet<DeviceTypeAndVoiceFilter>();
            DeviceTypeAndWardrobe = new HashSet<DeviceTypeAndWardrobe>();
            InverseParentNavigation = new HashSet<DeviceType>();
            PriceruleAndDeviceType = new HashSet<PriceruleAndDeviceType>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long? Parent { get; set; }

        public virtual DeviceType ParentNavigation { get; set; }
        public virtual ICollection<CampaignAndDeviceType> CampaignAndDeviceType { get; set; }
        public virtual ICollection<DeviceTypeAndAutoclip> DeviceTypeAndAutoclip { get; set; }
        public virtual ICollection<DeviceTypeAndBodyAnimation> DeviceTypeAndBodyAnimation { get; set; }
        public virtual ICollection<DeviceTypeAndCameraFilter> DeviceTypeAndCameraFilter { get; set; }
        public virtual ICollection<DeviceTypeAndCharacter> DeviceTypeAndCharacter { get; set; }
        public virtual ICollection<DeviceTypeAndPipeline> DeviceTypeAndPipeline { get; set; }
        public virtual ICollection<DeviceTypeAndProp> DeviceTypeAndProp { get; set; }
        public virtual ICollection<DeviceTypeAndScore> DeviceTypeAndScore { get; set; }
        public virtual ICollection<DeviceTypeAndSetLocation> DeviceTypeAndSetLocation { get; set; }
        public virtual ICollection<DeviceTypeAndSong> DeviceTypeAndSong { get; set; }
        public virtual ICollection<DeviceTypeAndSticker> DeviceTypeAndSticker { get; set; }
        public virtual ICollection<DeviceTypeAndVfx> DeviceTypeAndVfx { get; set; }
        public virtual ICollection<DeviceTypeAndVoiceFilter> DeviceTypeAndVoiceFilter { get; set; }
        public virtual ICollection<DeviceTypeAndWardrobe> DeviceTypeAndWardrobe { get; set; }
        public virtual ICollection<DeviceType> InverseParentNavigation { get; set; }
        public virtual ICollection<PriceruleAndDeviceType> PriceruleAndDeviceType { get; set; }
    }
}