// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class DeviceTypeAndWardrobe
    {
        public long DeviceTypeId { get; set; }
        public long WardrobeId { get; set; }

        public virtual DeviceType DeviceType { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}