// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class EventAndEventSpecialAssetbundle
    {
        public long EventId { get; set; }
        public long SpecialAssetbundleId { get; set; }

        public virtual Event Event { get; set; }
        public virtual EventSpecialAssetbundle SpecialAssetbundle { get; set; }
    }
}