// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class ExtremeExpressionBundle
    {
        public ExtremeExpressionBundle()
        {
            ExtremeExpression = new HashSet<ExtremeExpression>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public string DisplayName { get; set; }
        public long ExtremeExpressionBundleCategoryId { get; set; }
        public long? Size { get; set; }
        public long UploaderUserId { get; set; }

        public virtual ExtremeExpressionBundleCategory ExtremeExpressionBundleCategory { get; set; }
        public virtual Group Group { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual ICollection<ExtremeExpression> ExtremeExpression { get; set; }
    }
}