// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Bridge.Models.AsseManager
{
    public partial class FollowerHistory
    {
        public long FollowerHistoryId { get; set; }
        public long FollowingId { get; set; }
        public long FollowerId { get; set; }
        public DateTime TimePeriod { get; set; }

        public virtual Group Follower { get; set; }
        public virtual Group Following { get; set; }
    }
}