// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Genre
    {
        public Genre()
        {
            BodyAnimationCategoryAndGenre = new HashSet<BodyAnimationCategoryAndGenre>();
            BrandAndGenre = new HashSet<BrandAndGenre>();
            SetLocationCategoryAndGenre = new HashSet<SetLocationCategoryAndGenre>();
            SetLocationMoodAndGenre = new HashSet<SetLocationMoodAndGenre>();
            Song = new HashSet<Song>();
            VfxCategoryAndGenre = new HashSet<VfxCategoryAndGenre>();
            WardrobeCollectionAndGenre = new HashSet<WardrobeCollectionAndGenre>();
            WardrobeStyleAndGenre = new HashSet<WardrobeStyleAndGenre>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public long LabelId { get; set; }

        public virtual Label Label { get; set; }
        public virtual ICollection<BodyAnimationCategoryAndGenre> BodyAnimationCategoryAndGenre { get; set; }
        public virtual ICollection<BrandAndGenre> BrandAndGenre { get; set; }
        public virtual ICollection<SetLocationCategoryAndGenre> SetLocationCategoryAndGenre { get; set; }
        public virtual ICollection<SetLocationMoodAndGenre> SetLocationMoodAndGenre { get; set; }
        public virtual ICollection<Song> Song { get; set; }
        public virtual ICollection<VfxCategoryAndGenre> VfxCategoryAndGenre { get; set; }
        public virtual ICollection<WardrobeCollectionAndGenre> WardrobeCollectionAndGenre { get; set; }
        public virtual ICollection<WardrobeStyleAndGenre> WardrobeStyleAndGenre { get; set; }
    }
}