// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class GroupAndLevel
    {
        public long GroupId { get; set; }
        public long LevelId { get; set; }

        public virtual Group Group { get; set; }
        public virtual Level Level { get; set; }
    }
}