// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Hashtag
    {
        public Hashtag()
        {
            LevelAndHashtag = new HashSet<LevelAndHashtag>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<LevelAndHashtag> LevelAndHashtag { get; set; }
    }
}