// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Level
    {
        public Level()
        {
            Event = new HashSet<Event>();
            GroupAndLevel = new HashSet<GroupAndLevel>();
            InverseRemixedFromLevel = new HashSet<Level>();
            LevelAbuseReport = new HashSet<LevelAbuseReport>();
            LevelAndHashtag = new HashSet<LevelAndHashtag>();
            LevelAndMultiLanguageLevel = new HashSet<LevelAndMultiLanguageLevel>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public long OriginalGroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long LevelTemplateId { get; set; }
        public long VerticalCategoryId { get; set; }
        public long LanguageId { get; set; }
        public long? RemixedFromLevelId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsDraft { get; set; }
        public bool IsConverting { get; set; }

        public virtual Group Group { get; set; }
        public virtual Language Language { get; set; }
        public virtual LevelTemplate LevelTemplate { get; set; }
        public virtual Group OriginalGroup { get; set; }
        public virtual Level RemixedFromLevel { get; set; }
        public virtual VerticalCategory VerticalCategory { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<GroupAndLevel> GroupAndLevel { get; set; }
        public virtual ICollection<Level> InverseRemixedFromLevel { get; set; }
        public virtual ICollection<LevelAbuseReport> LevelAbuseReport { get; set; }
        public virtual ICollection<LevelAndHashtag> LevelAndHashtag { get; set; }
        public virtual ICollection<LevelAndMultiLanguageLevel> LevelAndMultiLanguageLevel { get; set; }
    }
}