// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class LevelAndMultiLanguageLevel
    {
        public long LevelId { get; set; }
        public long MultiLanguageLevelId { get; set; }

        public virtual Level Level { get; set; }
        public virtual MultiLanguageLevel MultiLanguageLevel { get; set; }
    }
}