// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Mood
    {
        public Mood()
        {
            Score = new HashSet<Score>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        
        public virtual ICollection<Song> Song { get; set; }
        public virtual ICollection<Score> Score { get; set; }
    }
}