// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class OutfitAndWardrobe
    {
        public long OutfitId { get; set; }
        public long WardrobeId { get; set; }

        public virtual Outfit Outfit { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}