// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Bridge.Models.AsseManager
{
    public partial class PayoutSchemeRevShare
    {
        public long Id { get; set; }
        public long PayoutSchemeId { get; set; }
        public int NumItemsRange { get; set; }
        public int RevSharePercent { get; set; }

        public virtual PayoutScheme PayoutScheme { get; set; }
    }
}