// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class PriceruleAndCharacter
    {
        public long PriceruleId { get; set; }
        public long CharacterId { get; set; }

        public virtual Character Character { get; set; }
        public virtual Pricerule Pricerule { get; set; }
    }
}