// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class PriceruleAndGroup
    {
        public long PriceruleId { get; set; }
        public long GroupId { get; set; }

        public virtual Group Group { get; set; }
        public virtual Pricerule Pricerule { get; set; }
    }
}