// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class PropCategory
    {
        public PropCategory()
        {
            BrandAndPropCategory = new HashSet<BrandAndPropCategory>();
            Prop = new HashSet<Prop>();
            PropSubCategory = new HashSet<PropSubCategory>();
            SetLocationCategoryAndPropCategory = new HashSet<SetLocationCategoryAndPropCategory>();
            SetLocationMoodAndPropCategory = new HashSet<SetLocationMoodAndPropCategory>();
            WardrobeCollectionAndPropCategory = new HashSet<WardrobeCollectionAndPropCategory>();
            WardrobeStyleAndPropCategory = new HashSet<WardrobeStyleAndPropCategory>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }

        public virtual ICollection<BrandAndPropCategory> BrandAndPropCategory { get; set; }
        public virtual ICollection<Prop> Prop { get; set; }
        public virtual ICollection<PropSubCategory> PropSubCategory { get; set; }
        public virtual ICollection<SetLocationCategoryAndPropCategory> SetLocationCategoryAndPropCategory { get; set; }
        public virtual ICollection<SetLocationMoodAndPropCategory> SetLocationMoodAndPropCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndPropCategory> WardrobeCollectionAndPropCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndPropCategory> WardrobeStyleAndPropCategory { get; set; }
    }
}