// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Readiness
    {
        public Readiness()
        {
            Autoclip = new HashSet<Autoclip>();
            BodyAnimation = new HashSet<AsseManager.BodyAnimation>();
            Bundle = new HashSet<Bundle>();
            CameraAnimationTemplate = new HashSet<CameraAnimationTemplate>();
            Character = new HashSet<Character>();
            ExtremeExpression = new HashSet<ExtremeExpression>();
            Outfit = new HashSet<Outfit>();
            Photo = new HashSet<Photo>();
            Prop = new HashSet<Prop>();
            Score = new HashSet<Score>();
            SetLocation = new HashSet<SetLocation>();
            SetLocationBundle = new HashSet<SetLocationBundle>();
            Sfx = new HashSet<Sfx>();
            Song = new HashSet<Song>();
            Sticker = new HashSet<Sticker>();
            Vfx = new HashSet<Vfx>();
            VideoClip = new HashSet<VideoClip>();
            VoiceFilter = new HashSet<VoiceFilter>();
            Wardrobe = new HashSet<Wardrobe>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Autoclip> Autoclip { get; set; }
        public virtual ICollection<AsseManager.BodyAnimation> BodyAnimation { get; set; }
        public virtual ICollection<Bundle> Bundle { get; set; }
        public virtual ICollection<CameraAnimationTemplate> CameraAnimationTemplate { get; set; }

        public virtual ICollection<CameraFilter> CameraFilter { get; set; }
        public virtual ICollection<Character> Character { get; set; }
        public virtual ICollection<ExtremeExpression> ExtremeExpression { get; set; }
        public virtual ICollection<Outfit> Outfit { get; set; }
        public virtual ICollection<Photo> Photo { get; set; }
        public virtual ICollection<Prop> Prop { get; set; }
        public virtual ICollection<Score> Score { get; set; }
        public virtual ICollection<SetLocation> SetLocation { get; set; }
        public virtual ICollection<SetLocationBundle> SetLocationBundle { get; set; }
        public virtual ICollection<Sfx> Sfx { get; set; }
        public virtual ICollection<Song> Song { get; set; }
        public virtual ICollection<Sticker> Sticker { get; set; }
        public virtual ICollection<Vfx> Vfx { get; set; }
        public virtual ICollection<VideoClip> VideoClip { get; set; }
        public virtual ICollection<VoiceFilter> VoiceFilter { get; set; }
        public virtual ICollection<Wardrobe> Wardrobe { get; set; }
    }
}