// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Score
    {
        public Score()
        {
            AccountTransactionAndScore = new HashSet<AccountTransactionAndScore>();
            BundleAndScore = new HashSet<BundleAndScore>();
            DeviceTypeAndScore = new HashSet<DeviceTypeAndScore>();
            GroupAndScore = new HashSet<GroupAndScore>();
            MusicController = new HashSet<MusicController>();
            PriceruleAndScore = new HashSet<PriceruleAndScore>();
            QaComments = new HashSet<QaComments>();
            SeasonAndScore = new HashSet<SeasonAndScore>();
            WardrobeAndScore = new HashSet<WardrobeAndScore>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long MoodId { get; set; }
        public long ArtistId { get; set; }
        public long LabelId { get; set; }
        public long GroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long ReadinessId { get; set; }
        public long? Size { get; set; }
        public int Channels { get; set; }
        public int SamplingSize { get; set; }
        public int Duration { get; set; }
        public int SamplingFrequency { get; set; }
        public string Name { get; set; }
        public long UploaderUserId { get; set; }
        public long[] Tags { get; set; }
        public string FilesInfo { get; set; }
        public int SortOrder { get; set; }

        public virtual Artist Artist { get; set; }
        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual Group Group { get; set; }
        public virtual Label Label { get; set; }
        public virtual Mood Mood { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual ICollection<AccountTransactionAndScore> AccountTransactionAndScore { get; set; }
        public virtual ICollection<BundleAndScore> BundleAndScore { get; set; }
        public virtual ICollection<DeviceTypeAndScore> DeviceTypeAndScore { get; set; }
        public virtual ICollection<GroupAndScore> GroupAndScore { get; set; }
        public virtual ICollection<MusicController> MusicController { get; set; }
        public virtual ICollection<PriceruleAndScore> PriceruleAndScore { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
        public virtual ICollection<SeasonAndScore> SeasonAndScore { get; set; }
        public virtual ICollection<WardrobeAndScore> WardrobeAndScore { get; set; }
    }
}