// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class ScoreCategory
    {
        public ScoreCategory()
        {
            BrandAndScoreCategory = new HashSet<BrandAndScoreCategory>();
            SetLocationCategoryAndScoreCategory = new HashSet<SetLocationCategoryAndScoreCategory>();
            SetLocationMoodAndScoreCategory = new HashSet<SetLocationMoodAndScoreCategory>();
            WardrobeCollectionAndScoreCategory = new HashSet<WardrobeCollectionAndScoreCategory>();
            WardrobeStyleAndScoreCategory = new HashSet<WardrobeStyleAndScoreCategory>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<BrandAndScoreCategory> BrandAndScoreCategory { get; set; }
        public virtual ICollection<SetLocationCategoryAndScoreCategory> SetLocationCategoryAndScoreCategory { get; set; }
        public virtual ICollection<SetLocationMoodAndScoreCategory> SetLocationMoodAndScoreCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndScoreCategory> WardrobeCollectionAndScoreCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndScoreCategory> WardrobeStyleAndScoreCategory { get; set; }
    }
}