// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SeasonAndSticker
    {
        public long SeasonId { get; set; }
        public long StickerId { get; set; }

        public virtual Season Season { get; set; }
        public virtual Sticker Sticker { get; set; }
    }
}