// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Season
    {
        public Season()
        {
            SeasonAndAutoclip = new HashSet<SeasonAndAutoclip>();
            SeasonAndBodyAnimation = new HashSet<SeasonAndBodyAnimation>();
            SeasonAndCameraFilter = new HashSet<SeasonAndCameraFilter>();
            SeasonAndCharacter = new HashSet<SeasonAndCharacter>();
            SeasonAndProp = new HashSet<SeasonAndProp>();
            SeasonAndScore = new HashSet<SeasonAndScore>();
            SeasonAndSetLocation = new HashSet<SeasonAndSetLocation>();
            SeasonAndSong = new HashSet<SeasonAndSong>();
            SeasonAndSticker = new HashSet<SeasonAndSticker>();
            SeasonAndVfx = new HashSet<SeasonAndVfx>();
            SeasonAndVoiceFilter = new HashSet<SeasonAndVoiceFilter>();
            SeasonAndWardrobe = new HashSet<SeasonAndWardrobe>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SeasonAndAutoclip> SeasonAndAutoclip { get; set; }
        public virtual ICollection<SeasonAndBodyAnimation> SeasonAndBodyAnimation { get; set; }
        public virtual ICollection<SeasonAndCameraFilter> SeasonAndCameraFilter { get; set; }
        public virtual ICollection<SeasonAndCharacter> SeasonAndCharacter { get; set; }
        public virtual ICollection<SeasonAndProp> SeasonAndProp { get; set; }
        public virtual ICollection<SeasonAndScore> SeasonAndScore { get; set; }
        public virtual ICollection<SeasonAndSetLocation> SeasonAndSetLocation { get; set; }
        public virtual ICollection<SeasonAndSong> SeasonAndSong { get; set; }
        public virtual ICollection<SeasonAndSticker> SeasonAndSticker { get; set; }
        public virtual ICollection<SeasonAndVfx> SeasonAndVfx { get; set; }
        public virtual ICollection<SeasonAndVoiceFilter> SeasonAndVoiceFilter { get; set; }
        public virtual ICollection<SeasonAndWardrobe> SeasonAndWardrobe { get; set; }
    }
}