// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SeasonAndAutoclip
    {
        public long SeasonId { get; set; }
        public long AutoclipId { get; set; }

        public virtual Autoclip Autoclip { get; set; }
        public virtual Season Season { get; set; }
    }
}