// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationSubCategory
    {
        public SetLocationSubCategory()
        {
            SetLocation = new HashSet<SetLocation>();
        }

        public long Id { get; set; }
        public long SetLocationCategoryId { get; set; }
        public string Name { get; set; }

        public virtual SetLocationCategory SetLocationCategory { get; set; }
        public virtual ICollection<SetLocation> SetLocation { get; set; }
    }
}