// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationMoodAndCameraFilterCategory
    {
        public long SetLocationMoodId { get; set; }
        public long CameraFilterCategoryId { get; set; }
        public int SetLocationMoodSortKey { get; set; }
        public int CameraFilterSortKey { get; set; }

        public virtual CameraFilterCategory CameraFilterCategory { get; set; }
        public virtual SetLocationMood SetLocationMood { get; set; }
    }
}