// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationMoodAndPropCategory
    {
        public long SetLocationMoodId { get; set; }
        public long PropCategoryId { get; set; }
        public int SetLocationMoodSortKey { get; set; }
        public int PropCategorySortKey { get; set; }

        public virtual PropCategory PropCategory { get; set; }
        public virtual SetLocationMood SetLocationMood { get; set; }
    }
}