// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationMoodAndSfxCategory
    {
        public long SetLocationMoodId { get; set; }
        public long SfxCategoryId { get; set; }
        public int SetLocationMoodSortKey { get; set; }
        public int SfxCategorySortKey { get; set; }

        public virtual SetLocationMood SetLocationMood { get; set; }
        public virtual SfxCategory SfxCategory { get; set; }
    }
}