// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationMoodAndScoreCategory
    {
        public long SetLocationMoodId { get; set; }
        public long ScoreCategoryId { get; set; }
        public int SetLocationMoodSortKey { get; set; }
        public int ScoreSortKey { get; set; }

        public virtual ScoreCategory ScoreCategory { get; set; }
        public virtual SetLocationMood SetLocationMood { get; set; }
    }
}