// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationMoodAndBodyAnimationCategory
    {
        public long SetLocationMoodId { get; set; }
        public long BodyAnimationCategoryId { get; set; }
        public int SetLocationMoodSortKey { get; set; }
        public int BodyAnimationCategorySortKey { get; set; }

        public virtual BodyAnimationCategory BodyAnimationCategory { get; set; }
        public virtual SetLocationMood SetLocationMood { get; set; }
    }
}