// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationCategoryAndSfxCategory
    {
        public long SetLocationCategoryId { get; set; }
        public long SfxCategoryId { get; set; }
        public int SetLocationCategorySortKey { get; set; }
        public int SfxCategorySortKey { get; set; }

        public virtual SetLocationCategory SetLocationCategory { get; set; }
        public virtual SfxCategory SfxCategory { get; set; }
    }
}