// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationMoodAndGenre
    {
        public long SetLocationMoodId { get; set; }
        public long GenreId { get; set; }
        public int SetLocationMoodSortKey { get; set; }
        public int GenreSortKey { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual SetLocationMood SetLocationMood { get; set; }
    }
}