// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationCategoryAndScoreCategory
    {
        public long SetLocationCategoryId { get; set; }
        public long ScoreCategoryId { get; set; }
        public int SetLocationCategorySortKey { get; set; }
        public int ScoreCategorySortKey { get; set; }

        public virtual ScoreCategory ScoreCategory { get; set; }
        public virtual SetLocationCategory SetLocationCategory { get; set; }
    }
}