// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationAndCharacterSpawnPosition
    {
        public long CharacterSpawnPositionId { get; set; }
        public long SetLocationId { get; set; }
        public int SortOrder { get; set; }

        public virtual CharacterSpawnPosition CharacterSpawnPosition { get; set; }
        public virtual SetLocation SetLocation { get; set; }
    }
}