// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class StickerController
    {
        public long Id { get; set; }
        public long EventId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public long StickerId { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }
        public int PositionX { get; set; }
        public int PositionY { get; set; }
        public int RotationDegrees { get; set; }
        public long FontId { get; set; }
        public int FontSize { get; set; }
        public string Text { get; set; }
        public int TextColor { get; set; }
        public int BackgroundColor { get; set; }
        
        public virtual Event Event { get; set; }
        public virtual Font Font { get; set; }
        public virtual Sticker Sticker { get; set; }
    }
}