// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Sticker
    {
        public Sticker()
        {
            AccountTransactionAndSticker = new HashSet<AccountTransactionAndSticker>();
            BundleAndSticker = new HashSet<BundleAndSticker>();
            DeviceTypeAndSticker = new HashSet<DeviceTypeAndSticker>();
            GroupAndSticker = new HashSet<GroupAndSticker>();
            PriceruleAndSticker = new HashSet<PriceruleAndSticker>();
            QaComments = new HashSet<QaComments>();
            SeasonAndSticker = new HashSet<SeasonAndSticker>();
            StickerController = new HashSet<StickerController>();
            WardrobeAndSticker = new HashSet<WardrobeAndSticker>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long GroupId { get; set; }
        public long StickerCategoryId { get; set; }
        public long? BrandId { get; set; }
        public long StickerSizeId { get; set; }
        public long ReadinessId { get; set; }
        public long? Size { get; set; }
        public string Name { get; set; }
        public long UploaderUserId { get; set; }
        public long[] Tags { get; set; }
        public int SortOrder { get; set; }

        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual StickerCategory StickerCategory { get; set; }
        public virtual StickerSize StickerSize { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual ICollection<AccountTransactionAndSticker> AccountTransactionAndSticker { get; set; }
        public virtual ICollection<BundleAndSticker> BundleAndSticker { get; set; }
        public virtual ICollection<DeviceTypeAndSticker> DeviceTypeAndSticker { get; set; }
        public virtual ICollection<GroupAndSticker> GroupAndSticker { get; set; }
        public virtual ICollection<PriceruleAndSticker> PriceruleAndSticker { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
        public virtual ICollection<SeasonAndSticker> SeasonAndSticker { get; set; }
        public virtual ICollection<StickerController> StickerController { get; set; }
        public virtual ICollection<WardrobeAndSticker> WardrobeAndSticker { get; set; }
    }
}