// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class TagPairs
    {
        public long Tag1 { get; set; }
        public long Tag2 { get; set; }

        public virtual Tag Tag1Navigation { get; set; }
        public virtual Tag Tag2Navigation { get; set; }
    }
}