// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Team
    {
        public Team()
        {
            CampaignAndTeam = new HashSet<CampaignAndTeam>();
            CharacterTeamPermission = new HashSet<CharacterTeamPermission>();
            PriceruleAndTeam = new HashSet<PriceruleAndTeam>();
            TeamMember = new HashSet<TeamMember>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long ManagerId { get; set; }
        public int MemberCount { get; set; }

        public virtual User Manager { get; set; }
        public virtual ICollection<CampaignAndTeam> CampaignAndTeam { get; set; }
        public virtual ICollection<CharacterTeamPermission> CharacterTeamPermission { get; set; }
        public virtual ICollection<PriceruleAndTeam> PriceruleAndTeam { get; set; }
        public virtual ICollection<TeamMember> TeamMember { get; set; }
    }
}