// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class TeamMember
    {
        public long UserId { get; set; }
        public long TeamId { get; set; }

        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}