// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class TransactionType
    {
        public TransactionType()
        {
            AccountTransaction = new HashSet<AccountTransaction>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }

        public virtual ICollection<AccountTransaction> AccountTransaction { get; set; }
    }
}