// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class UmaAsset
    {
        public UmaAsset()
        {
            UmaAssetFile = new HashSet<UmaAssetFile>();
            UmaAssetWardrobeCompatibilityCompatibleUmaAssetNavigation = new HashSet<UmaAssetWardrobeCompatibility>();
            UmaAssetWardrobeCompatibilityTargetUmaAssetNavigation = new HashSet<UmaAssetWardrobeCompatibility>();
            UmaAssetWardrobeHidesHiddenUmaAssetNavigation = new HashSet<UmaAssetWardrobeHides>();
            UmaAssetWardrobeHidesTargetUmaAssetNavigation = new HashSet<UmaAssetWardrobeHides>();
        }

        public long Id { get; set; }
        public string AssetName { get; set; }
        public long AssetHash { get; set; }
        public long? AssetWardrobeSlotId { get; set; }
        public long UmaBundleId { get; set; }

        public virtual AssetWardrobeSlot AssetWardrobeSlot { get; set; }
        public virtual UmaBundle UmaBundle { get; set; }
        public virtual ICollection<UmaAssetFile> UmaAssetFile { get; set; }
        public virtual ICollection<UmaAssetWardrobeCompatibility> UmaAssetWardrobeCompatibilityCompatibleUmaAssetNavigation { get; set; }
        public virtual ICollection<UmaAssetWardrobeCompatibility> UmaAssetWardrobeCompatibilityTargetUmaAssetNavigation { get; set; }
        public virtual ICollection<UmaAssetWardrobeHides> UmaAssetWardrobeHidesHiddenUmaAssetNavigation { get; set; }
        public virtual ICollection<UmaAssetWardrobeHides> UmaAssetWardrobeHidesTargetUmaAssetNavigation { get; set; }
    }
}