// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class UmaAssetWardrobeCompatibility
    {
        public long TargetUmaAsset { get; set; }
        public long CompatibleUmaAsset { get; set; }

        public virtual UmaAsset CompatibleUmaAssetNavigation { get; set; }
        public virtual UmaAsset TargetUmaAssetNavigation { get; set; }
    }
}