// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class UmaBundleDirectDependency
    {
        public long UmaBundleId { get; set; }
        public long DependsOnBundleId { get; set; }

        public virtual UmaBundle DependsOnBundle { get; set; }
        public virtual UmaBundle UmaBundle { get; set; }
    }
}