// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class UmaRecipe
    {
        public UmaRecipe()
        {
            CharacterAndUmaRecipe = new HashSet<CharacterAndUmaRecipe>();
            CharacterControllerBackgroundDancer = new HashSet<CharacterControllerBackgroundDancer>();
            CharacterControllerUmaRecipe = new HashSet<CharacterControllerUmaRecipe>();
            UmaRecipeAndWardrobe = new HashSet<UmaRecipeAndWardrobe>();
        }

        public long Id { get; set; }
        public Guid GlobalId { get; set; }
        public byte[] J { get; set; }

        public virtual ICollection<CharacterAndUmaRecipe> CharacterAndUmaRecipe { get; set; }
        public virtual ICollection<CharacterControllerBackgroundDancer> CharacterControllerBackgroundDancer { get; set; }
        public virtual ICollection<CharacterControllerUmaRecipe> CharacterControllerUmaRecipe { get; set; }
        public virtual ICollection<UmaRecipeAndWardrobe> UmaRecipeAndWardrobe { get; set; }
    }
}