// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class UmaRecipeAndWardrobe
    {
        public long UmaRecipeId { get; set; }
        public long WardrobeId { get; set; }

        public virtual UmaRecipe UmaRecipe { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}