// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class User
    {
        public User()
        {
            Autoclip = new HashSet<Autoclip>();
            BodyAnimation = new HashSet<AsseManager.BodyAnimation>();
            CameraAnimationTemplate = new HashSet<CameraAnimationTemplate>();
            CameraFilter = new HashSet<CameraFilter>();
            CampaignAndUser = new HashSet<CampaignAndUser>();
            Character = new HashSet<Character>();
            Crowd = new HashSet<Crowd>();
            CrowdMovement = new HashSet<CrowdMovement>();
            ExtremeExpressionBundle = new HashSet<ExtremeExpressionBundle>();
            FaceAnimation = new HashSet<FaceAnimation>();
            Group = new HashSet<Group>();
            LevelAbuseReportAssignedToUser = new HashSet<LevelAbuseReport>();
            LevelAbuseReportUser = new HashSet<LevelAbuseReport>();
            Photo = new HashSet<Photo>();
            PriceruleAndUser = new HashSet<PriceruleAndUser>();
            Prop = new HashSet<Prop>();
            QaCommentsCommentByNavigation = new HashSet<QaComments>();
            QaCommentsResolvedByNavigation = new HashSet<QaComments>();
            Score = new HashSet<Score>();
            SetLocation = new HashSet<SetLocation>();
            Sfx = new HashSet<Sfx>();
            Song = new HashSet<Song>();
            Sticker = new HashSet<Sticker>();
            Team = new HashSet<Team>();
            TeamMember = new HashSet<TeamMember>();
            UserAndGroup = new HashSet<UserAndGroup>();
            Vfx = new HashSet<Vfx>();
            VideoClip = new HashSet<VideoClip>();
            VoiceFilter = new HashSet<VoiceFilter>();
            Wardrobe = new HashSet<Wardrobe>();
        }

        public long Id { get; set; }
        public Guid IdentityServerId { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime? ConsentTime { get; set; }
        public DateTime CreatedTime { get; set; }
        public long[] CreatorPermissionLevel { get; set; }
        public bool Artist { get; set; }
        public bool Qauser { get; set; }
        public bool Partner { get; set; }
        public bool Moderator { get; set; }
        public long? MainCharacterId { get; set; }
        public bool? DataCollection { get; set; }
        public long MainGroupId { get; set; }
        public bool IsFeatured { get; set; }
        public bool AnalyticsEnabled { get; set; }
        public bool IsEmployee { get; set; }

        public virtual Character MainCharacter { get; set; }
        public virtual Group MainGroup { get; set; }
        public virtual ICollection<Autoclip> Autoclip { get; set; }
        public virtual ICollection<AsseManager.BodyAnimation> BodyAnimation { get; set; }
        public virtual ICollection<CameraAnimationTemplate> CameraAnimationTemplate { get; set; }
        public virtual ICollection<CameraFilter> CameraFilter { get; set; }
        public virtual ICollection<CampaignAndUser> CampaignAndUser { get; set; }
        public virtual ICollection<Character> Character { get; set; }
        public virtual ICollection<Crowd> Crowd { get; set; }
        public virtual ICollection<CrowdMovement> CrowdMovement { get; set; }
        public virtual ICollection<ExtremeExpressionBundle> ExtremeExpressionBundle { get; set; }
        public virtual ICollection<FaceAnimation> FaceAnimation { get; set; }
        public virtual ICollection<Group> Group { get; set; }
        public virtual ICollection<LevelAbuseReport> LevelAbuseReportAssignedToUser { get; set; }
        public virtual ICollection<LevelAbuseReport> LevelAbuseReportUser { get; set; }
        public virtual ICollection<Photo> Photo { get; set; }
        public virtual ICollection<PriceruleAndUser> PriceruleAndUser { get; set; }
        public virtual ICollection<Prop> Prop { get; set; }
        public virtual ICollection<QaComments> QaCommentsCommentByNavigation { get; set; }
        public virtual ICollection<QaComments> QaCommentsResolvedByNavigation { get; set; }
        public virtual ICollection<Score> Score { get; set; }
        public virtual ICollection<SetLocation> SetLocation { get; set; }
        public virtual ICollection<Sfx> Sfx { get; set; }
        public virtual ICollection<Song> Song { get; set; }
        public virtual ICollection<Sticker> Sticker { get; set; }
        public virtual ICollection<Team> Team { get; set; }
        public virtual ICollection<TeamMember> TeamMember { get; set; }
        public virtual ICollection<UserAndGroup> UserAndGroup { get; set; }
        public virtual ICollection<Vfx> Vfx { get; set; }
        public virtual ICollection<VideoClip> VideoClip { get; set; }
        public virtual ICollection<VoiceFilter> VoiceFilter { get; set; }
        public virtual ICollection<Wardrobe> Wardrobe { get; set; }
    }
}