// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class UserSound
    {
        public UserSound()
        {
            MusicController = new HashSet<MusicController>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public long? Size { get; set; }
        public int Duration { get; set; }
        public string FilesInfo { get; set; }

        public virtual Group Group { get; set; }
        public virtual ICollection<MusicController> MusicController { get; set; }
    }
}