// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class VerticalCategory
    {
        public VerticalCategory()
        {
            CampaignAndVerticalCategory = new HashSet<CampaignAndVerticalCategory>();
            Level = new HashSet<Level>();
            PriceruleAndVerticalCategory = new HashSet<PriceruleAndVerticalCategory>();
        }

        public long Id { get; set; }
        public long VerticalId { get; set; }
        public string Name { get; set; }

        public virtual Vertical Vertical { get; set; }
        public virtual ICollection<CampaignAndVerticalCategory> CampaignAndVerticalCategory { get; set; }
        public virtual ICollection<Level> Level { get; set; }
        public virtual ICollection<PriceruleAndVerticalCategory> PriceruleAndVerticalCategory { get; set; }
    }
}