// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Vfx
    {
        public Vfx()
        {
            AccountTransactionAndVfx = new HashSet<AccountTransactionAndVfx>();
            BundleAndVfx = new HashSet<BundleAndVfx>();
            CharacterControllerFaceVoice = new HashSet<CharacterControllerFaceVoice>();
            DeviceTypeAndVfx = new HashSet<DeviceTypeAndVfx>();
            GroupAndVfx = new HashSet<GroupAndVfx>();
            LevelTemplateAndVfx = new HashSet<LevelTemplateAndVfx>();
            PriceruleAndVfx = new HashSet<PriceruleAndVfx>();
            QaComments = new HashSet<QaComments>();
            SeasonAndVfx = new HashSet<SeasonAndVfx>();
            VfxController = new HashSet<VfxController>();
            WardrobeAndVfx = new HashSet<WardrobeAndVfx>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long VfxCategoryId { get; set; }
        public long VfxTypeId { get; set; }
        public long GroupId { get; set; }
        public long ReadinessId { get; set; }
        public long VfxDirectionId { get; set; }
        public long VfxWorldSizeId { get; set; }
        public bool Looping { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long SizeKb { get; set; }
        public int? PolyCount { get; set; }
        public int? Duration { get; set; }
        public string Name { get; set; }
        public long UploaderUserId { get; set; }
        public bool IsDefault { get; set; }
        public bool IsStartPackMember { get; set; }
        public long[] Tags { get; set; }
        public string FilesInfo { get; set; }
        public int SortOrder { get; set; }
        public long? AssetTierId { get; set; }
        public bool FollowRotation { get; set; }
        public string AnchorPoint { get; set; }

        public virtual AssetTier AssetTier { get; set; }
        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual VfxCategory VfxCategory { get; set; }
        public virtual VfxDirection VfxDirection { get; set; }
        public virtual VfxType VfxType { get; set; }
        public virtual VfxWorldSize VfxWorldSize { get; set; }
        public virtual ICollection<AccountTransactionAndVfx> AccountTransactionAndVfx { get; set; }
        public virtual ICollection<BundleAndVfx> BundleAndVfx { get; set; }
        public virtual ICollection<CharacterControllerFaceVoice> CharacterControllerFaceVoice { get; set; }
        public virtual ICollection<DeviceTypeAndVfx> DeviceTypeAndVfx { get; set; }
        public virtual ICollection<GroupAndVfx> GroupAndVfx { get; set; }
        public virtual ICollection<LevelTemplateAndVfx> LevelTemplateAndVfx { get; set; }
        public virtual ICollection<PriceruleAndVfx> PriceruleAndVfx { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
        public virtual ICollection<SeasonAndVfx> SeasonAndVfx { get; set; }
        public virtual ICollection<VfxController> VfxController { get; set; }
        public virtual ICollection<WardrobeAndVfx> WardrobeAndVfx { get; set; }
    }
}