// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class VfxCategoryAndGenre
    {
        public long VfxCategoryId { get; set; }
        public long GenreId { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual VfxCategory VfxCategory { get; set; }
    }
}