// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class VfxController
    {
        public long Id { get; set; }
        public long EventId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public long VfxId { get; set; }
        public int AnimationSpeed { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }
        public bool Looping { get; set; }

        public virtual Event Event { get; set; }
        public virtual Vfx Vfx { get; set; }
    }
}