// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class VfxPositionGroupAndVfxSpawnPosition
    {
        public long VfxPositionGroupId { get; set; }
        public long VfxSpawnPositionId { get; set; }

        public virtual VfxPositionGroup VfxPositionGroup { get; set; }
        public virtual VfxSpawnPosition VfxSpawnPosition { get; set; }
    }
}