// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class VoiceTrack
    {
        public VoiceTrack()
        {
            CharacterControllerFaceVoice = new HashSet<CharacterControllerFaceVoice>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long LanguageId { get; set; }
        public long GroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long? Size { get; set; }
        public int? Channels { get; set; }
        public int? SamplingSize { get; set; }
        public int Duration { get; set; }
        public int? SamplingFrequency { get; set; }
        public string FilesInfo { get; set; }

        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual Group Group { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<CharacterControllerFaceVoice> CharacterControllerFaceVoice { get; set; }
    }
}