// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeSubCategoryAndUmaAdjustment
    {
        public long WardrobeSubCategoryId { get; set; }
        public long UmaAdjustmentId { get; set; }

        public virtual UmaAdjustment UmaAdjustment { get; set; }
        public virtual WardrobeSubCategory WardrobeSubCategory { get; set; }
    }
}