// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeAndVfx
    {
        public long WardrobeId { get; set; }
        public long VfxId { get; set; }

        public virtual Vfx Vfx { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}