// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeStyleAndGenre
    {
        public long WardrobeStyleId { get; set; }
        public long GenreId { get; set; }
        public int WardrobeStyleSortKey { get; set; }
        public int GenreSortKey { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual WardrobeStyle WardrobeStyle { get; set; }
    }
}