// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeStyle
    {
        public WardrobeStyle()
        {
            Wardrobe = new HashSet<Wardrobe>();
            WardrobeStyleAndBodyAnimationCategory = new HashSet<WardrobeStyleAndBodyAnimationCategory>();
            WardrobeStyleAndCameraFilterCategory = new HashSet<WardrobeStyleAndCameraFilterCategory>();
            WardrobeStyleAndGenre = new HashSet<WardrobeStyleAndGenre>();
            WardrobeStyleAndPropCategory = new HashSet<WardrobeStyleAndPropCategory>();
            WardrobeStyleAndScoreCategory = new HashSet<WardrobeStyleAndScoreCategory>();
            WardrobeStyleAndSetLocationCategory = new HashSet<WardrobeStyleAndSetLocationCategory>();
            WardrobeStyleAndSetLocationMood = new HashSet<WardrobeStyleAndSetLocationMood>();
            WardrobeStyleAndSfxCategory = new HashSet<WardrobeStyleAndSfxCategory>();
            WardrobeStyleAndVfxCategory = new HashSet<WardrobeStyleAndVfxCategory>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Wardrobe> Wardrobe { get; set; }
        public virtual ICollection<WardrobeStyleAndBodyAnimationCategory> WardrobeStyleAndBodyAnimationCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndCameraFilterCategory> WardrobeStyleAndCameraFilterCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndGenre> WardrobeStyleAndGenre { get; set; }
        public virtual ICollection<WardrobeStyleAndPropCategory> WardrobeStyleAndPropCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndScoreCategory> WardrobeStyleAndScoreCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndSetLocationCategory> WardrobeStyleAndSetLocationCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndSetLocationMood> WardrobeStyleAndSetLocationMood { get; set; }
        public virtual ICollection<WardrobeStyleAndSfxCategory> WardrobeStyleAndSfxCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndVfxCategory> WardrobeStyleAndVfxCategory { get; set; }
    }
}