// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeStyleAndScoreCategory
    {
        public long WardrobeStyleId { get; set; }
        public long ScoreCategoryId { get; set; }
        public int WardrobeStyleSortKey { get; set; }
        public int ScoreCategorySortKey { get; set; }

        public virtual ScoreCategory ScoreCategory { get; set; }
        public virtual WardrobeStyle WardrobeStyle { get; set; }
    }
}