// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeAndSticker
    {
        public long WardrobeId { get; set; }
        public long StickerId { get; set; }

        public virtual Sticker Sticker { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}