// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeCollectionAndSfxCategory
    {
        public long WardrobeCollectionId { get; set; }
        public long SfxCategoryId { get; set; }
        public int WardrobeCollectionSortKey { get; set; }
        public int SfxCategorySortKey { get; set; }

        public virtual SfxCategory SfxCategory { get; set; }
        public virtual WardrobeCollection WardrobeCollection { get; set; }
    }
}