// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeCategory
    {
        public WardrobeCategory()
        {
            Wardrobe = new HashSet<Wardrobe>();
            WardrobeSubCategory = new HashSet<WardrobeSubCategory>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long WardrobeCategoryTypeId { get; set; }
        public string FilesInfo { get; set; }
        public int SortOrder { get; set; }
        public bool HasSubCategoryAll { get; set; }

        public virtual WardrobeCategoryType WardrobeCategoryType { get; set; }
        public virtual ICollection<Wardrobe> Wardrobe { get; set; }
        public virtual ICollection<WardrobeSubCategory> WardrobeSubCategory { get; set; }
    }
}