// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeAndSfx
    {
        public long WardrobeId { get; set; }
        public long SfxId { get; set; }

        public virtual Sfx Sfx { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}