// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeAndProp
    {
        public long WardrobeId { get; set; }
        public long PropId { get; set; }

        public virtual Prop Prop { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}