// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeStyleAndSetLocationMood
    {
        public long WardrobeStyleId { get; set; }
        public long SetLocationMoodId { get; set; }
        public int WardrobeStyleSortKey { get; set; }
        public int SetLocationMoodSortKey { get; set; }

        public virtual SetLocationMood SetLocationMood { get; set; }
        public virtual WardrobeStyle WardrobeStyle { get; set; }
    }
}