// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeStyleAndBodyAnimationCategory
    {
        public long WardrobeStyleId { get; set; }
        public long BodyAnimationCategoryId { get; set; }
        public int WardrobeStyleSortKey { get; set; }
        public int BodyAnimationCategorySortKey { get; set; }

        public virtual BodyAnimationCategory BodyAnimationCategory { get; set; }
        public virtual WardrobeStyle WardrobeStyle { get; set; }
    }
}