// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Wardrobe
    {
        public Wardrobe()
        {
            AccountTransactionAndWardrobe = new HashSet<AccountTransactionAndWardrobe>();
            BundleAndWardrobe = new HashSet<BundleAndWardrobe>();
            DeviceTypeAndWardrobe = new HashSet<DeviceTypeAndWardrobe>();
            GroupAndWardrobe = new HashSet<GroupAndWardrobe>();
            OutfitAndWardrobe = new HashSet<OutfitAndWardrobe>();
            PriceruleAndWardrobe = new HashSet<PriceruleAndWardrobe>();
            QaComments = new HashSet<QaComments>();
            SeasonAndWardrobe = new HashSet<SeasonAndWardrobe>();
            UmaRecipeAndWardrobe = new HashSet<UmaRecipeAndWardrobe>();
            WardrobeAndBodyAnimation = new HashSet<WardrobeAndBodyAnimation>();
            WardrobeAndCameraFilter = new HashSet<WardrobeAndCameraFilter>();
            WardrobeAndProp = new HashSet<WardrobeAndProp>();
            WardrobeAndScore = new HashSet<WardrobeAndScore>();
            WardrobeAndSetLocation = new HashSet<WardrobeAndSetLocation>();
            WardrobeAndSfx = new HashSet<WardrobeAndSfx>();
            WardrobeAndSong = new HashSet<WardrobeAndSong>();
            WardrobeAndSticker = new HashSet<WardrobeAndSticker>();
            WardrobeAndVfx = new HashSet<WardrobeAndVfx>();
            WardrobeAndVoiceFilter = new HashSet<WardrobeAndVoiceFilter>();
            WardrobeAndWardrobeSubCategory = new HashSet<WardrobeAndWardrobeSubCategory>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long GroupId { get; set; }
        public long WardrobeCategoryId { get; set; }
        public long WardrobeStyleId { get; set; }
        public long? WardrobeCollectionId { get; set; }
        public long? BrandId { get; set; }
        public long ReadinessId { get; set; }
        public DateTime CreatedTime { get; set; }
        public int? PolyCount { get; set; }
        public string Name { get; set; }
        public long UmaBundleId { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long UploaderUserId { get; set; }
        public long GenderId { get; set; }
        public bool OverridesLowerUnderwear { get; set; }
        public bool OverridesUpperUnderwear { get; set; }
        public bool IsStartPackMember { get; set; }
        public long[] Tags { get; set; }
        public long? WardrobeGenderGroupId { get; set; }
        public long? AssetTierId { get; set; }
        public string FilesInfo { get; set; }
        public long[] CompatibleGenderIds { get; set; }

        public virtual AssetTier AssetTier { get; set; }
        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual UmaBundle UmaBundle { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual WardrobeCategory WardrobeCategory { get; set; }
        public virtual WardrobeCollection WardrobeCollection { get; set; }
        public virtual WardrobeGenderGroup WardrobeGenderGroup { get; set; }
        public virtual WardrobeStyle WardrobeStyle { get; set; }
        public virtual ICollection<WardrobeAndWardrobeSubCategory> WardrobeAndWardrobeSubCategory { get; set; }
        public virtual ICollection<AccountTransactionAndWardrobe> AccountTransactionAndWardrobe { get; set; }
        public virtual ICollection<BundleAndWardrobe> BundleAndWardrobe { get; set; }
        public virtual ICollection<DeviceTypeAndWardrobe> DeviceTypeAndWardrobe { get; set; }
        public virtual ICollection<GroupAndWardrobe> GroupAndWardrobe { get; set; }
        public virtual ICollection<OutfitAndWardrobe> OutfitAndWardrobe { get; set; }
        public virtual ICollection<PriceruleAndWardrobe> PriceruleAndWardrobe { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
        public virtual ICollection<SeasonAndWardrobe> SeasonAndWardrobe { get; set; }
        public virtual ICollection<UmaRecipeAndWardrobe> UmaRecipeAndWardrobe { get; set; }
        public virtual ICollection<WardrobeAndBodyAnimation> WardrobeAndBodyAnimation { get; set; }
        public virtual ICollection<WardrobeAndCameraFilter> WardrobeAndCameraFilter { get; set; }
        public virtual ICollection<WardrobeAndProp> WardrobeAndProp { get; set; }
        public virtual ICollection<WardrobeAndScore> WardrobeAndScore { get; set; }
        public virtual ICollection<WardrobeAndSetLocation> WardrobeAndSetLocation { get; set; }
        public virtual ICollection<WardrobeAndSfx> WardrobeAndSfx { get; set; }
        public virtual ICollection<WardrobeAndSong> WardrobeAndSong { get; set; }
        public virtual ICollection<WardrobeAndSticker> WardrobeAndSticker { get; set; }
        public virtual ICollection<WardrobeAndVfx> WardrobeAndVfx { get; set; }
        public virtual ICollection<WardrobeAndVoiceFilter> WardrobeAndVoiceFilter { get; set; }
    }
}