// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeCollectionAndSetLocationCategory
    {
        public long WardrobeCollectionId { get; set; }
        public long SetLocationCategoryId { get; set; }
        public int WardrobeCollectionSortKey { get; set; }
        public int SetLocationCategorySortKey { get; set; }

        public virtual SetLocationCategory SetLocationCategory { get; set; }
        public virtual WardrobeCollection WardrobeCollection { get; set; }
    }
}