// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeStyleAndCameraFilterCategory
    {
        public long WardrobeStyleId { get; set; }
        public long CameraFilterCategoryId { get; set; }
        public int WardrobeStyleSortKey { get; set; }
        public int CmeraFilterCategorySortKey { get; set; }

        public virtual CameraFilterCategory CameraFilterCategory { get; set; }
        public virtual WardrobeStyle WardrobeStyle { get; set; }
    }
}