// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeCollectionAndVfxCategory
    {
        public long WardrobeCollectionId { get; set; }
        public long VfxCategoryId { get; set; }
        public int WardrobeCollectionSortKey { get; set; }
        public int VfxCategorySortKey { get; set; }

        public virtual VfxCategory VfxCategory { get; set; }
        public virtual WardrobeCollection WardrobeCollection { get; set; }
    }
}