// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeStyleAndSetLocationCategory
    {
        public long WardrobeStyleId { get; set; }
        public long SetLocationCategoryId { get; set; }
        public int WardrobeStyleSortKey { get; set; }
        public int SetLocationCategorySortKey { get; set; }

        public virtual SetLocationCategory SetLocationCategory { get; set; }
        public virtual WardrobeStyle WardrobeStyle { get; set; }
    }
}