// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Weather
    {
        public Weather()
        {
            SetLocation = new HashSet<SetLocation>();
            SetLocationController = new HashSet<SetLocationController>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SetLocation> SetLocation { get; set; }
        public virtual ICollection<SetLocationController> SetLocationController { get; set; }
    }
}