// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WithdrawalBlock
    {
        public long Id { get; set; }
        public long CurrencyId { get; set; }
        public long BlockValue { get; set; }
        public decimal Cost { get; set; }

        public virtual Currency Currency { get; set; }
    }
}