// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class AccountTransaction
    {
        public long Id { get; set; }
        public DateTime Timestamp { get; set; }
        public long AmountPaidfor { get; set; }
        public long AmountGiven { get; set; }
        public long DiscountAmount { get; set; }
        public long TransactionTypeId { get; set; }
        public string Description { get; set; }

        public virtual TransactionType TransactionType { get; set; }
        public virtual AccountTransactionAndAutoclip AccountTransactionAndAutoclip { get; set; }
        public virtual AccountTransactionAndBodyAnimation AccountTransactionAndBodyAnimation { get; set; }
        public virtual AccountTransactionAndBundle AccountTransactionAndBundle { get; set; }
        public virtual AccountTransactionAndCameraFilter AccountTransactionAndCameraFilter { get; set; }
        public virtual AccountTransactionAndCharacter AccountTransactionAndCharacter { get; set; }
        public virtual AccountTransactionAndProp AccountTransactionAndProp { get; set; }
        public virtual AccountTransactionAndScore AccountTransactionAndScore { get; set; }
        public virtual AccountTransactionAndSetLocation AccountTransactionAndSetLocation { get; set; }
        public virtual AccountTransactionAndSong AccountTransactionAndSong { get; set; }
        public virtual AccountTransactionAndSticker AccountTransactionAndSticker { get; set; }
        public virtual AccountTransactionAndVfx AccountTransactionAndVfx { get; set; }
        public virtual AccountTransactionAndVoiceFilter AccountTransactionAndVoiceFilter { get; set; }
        public virtual AccountTransactionAndWardrobe AccountTransactionAndWardrobe { get; set; }
        public virtual ExchangeTransaction ExchangeTransaction { get; set; }
    }
}