// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class AwardedBadge
    {
        public long GroupId { get; set; }
        public long BadgeId { get; set; }
        public DateTime AwardedTime { get; set; }

        public virtual Badge Badge { get; set; }
        public virtual Group Group { get; set; }
    }
}