// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Badge
    {
        public Badge()
        {
            AwardedBadge = new HashSet<AwardedBadge>();
            Campaign = new HashSet<Campaign>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<AwardedBadge> AwardedBadge { get; set; }
        public virtual ICollection<Campaign> Campaign { get; set; }
    }
}