// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BodyAnimationAndBodyAnimationCategory
    {
        public long BodyAnimationId { get; set; }
        public long BodyAnimationCategoryId { get; set; }
        public int CategorySortOrder { get; set; }

        public virtual AsseManager.BodyAnimation BodyAnimation { get; set; }
        public virtual BodyAnimationCategory BodyAnimationCategory { get; set; }
    }
}