// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BodyAnimationSpaceSize
    {
        public BodyAnimationSpaceSize()
        {
            BodyAnimation = new HashSet<AsseManager.BodyAnimation>();
            CharacterSpawnPosition = new HashSet<CharacterSpawnPosition>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long Size { get; set; }

        public virtual ICollection<AsseManager.BodyAnimation> BodyAnimation { get; set; }
        public virtual ICollection<CharacterSpawnPosition> CharacterSpawnPosition { get; set; }
    }
}