// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BodyAnimationCategory
    {
        public BodyAnimationCategory()
        {
            BodyAnimation = new HashSet<AsseManager.BodyAnimation>();
            BodyAnimationAndBodyAnimationCategory = new HashSet<BodyAnimationAndBodyAnimationCategory>();
            BodyAnimationCategoryAndGenre = new HashSet<BodyAnimationCategoryAndGenre>();
            SetLocationCategoryAndBodyAnimationCategory = new HashSet<SetLocationCategoryAndBodyAnimationCategory>();
            SetLocationMoodAndBodyAnimationCategory = new HashSet<SetLocationMoodAndBodyAnimationCategory>();
            WardrobeCollectionAndBodyAnimationCategory = new HashSet<WardrobeCollectionAndBodyAnimationCategory>();
            WardrobeStyleAndBodyAnimationCategory = new HashSet<WardrobeStyleAndBodyAnimationCategory>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }

        public virtual ICollection<AsseManager.BodyAnimation> BodyAnimation { get; set; }
        public virtual ICollection<BodyAnimationAndBodyAnimationCategory> BodyAnimationAndBodyAnimationCategory { get; set; }
        public virtual ICollection<BodyAnimationCategoryAndGenre> BodyAnimationCategoryAndGenre { get; set; }
        public virtual ICollection<SetLocationCategoryAndBodyAnimationCategory> SetLocationCategoryAndBodyAnimationCategory { get; set; }
        public virtual ICollection<SetLocationMoodAndBodyAnimationCategory> SetLocationMoodAndBodyAnimationCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndBodyAnimationCategory> WardrobeCollectionAndBodyAnimationCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndBodyAnimationCategory> WardrobeStyleAndBodyAnimationCategory { get; set; }
    }
}