// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BrandAndSetLocationMood
    {
        public long BrandId { get; set; }
        public long SetLocationMoodId { get; set; }
        public int BrandSortKey { get; set; }
        public int SetLocationMoodSortKey { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual SetLocationMood SetLocationMood { get; set; }
    }
}