// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class BrandAndScoreCategory
    {
        public long BrandId { get; set; }
        public long ScoreCategoryId { get; set; }
        public int BrandSortKey { get; set; }
        public int ScoreSortKey { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual ScoreCategory ScoreCategory { get; set; }
    }
}