// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Bundle
    {
        public Bundle()
        {
            AccountTransactionAndBundle = new HashSet<AccountTransactionAndBundle>();
            BundleAndAutoclip = new HashSet<BundleAndAutoclip>();
            BundleAndBodyAnimation = new HashSet<BundleAndBodyAnimation>();
            BundleAndCameraFilter = new HashSet<BundleAndCameraFilter>();
            BundleAndCharacter = new HashSet<BundleAndCharacter>();
            BundleAndProp = new HashSet<BundleAndProp>();
            BundleAndScore = new HashSet<BundleAndScore>();
            BundleAndSetLocation = new HashSet<BundleAndSetLocation>();
            BundleAndSong = new HashSet<BundleAndSong>();
            BundleAndSticker = new HashSet<BundleAndSticker>();
            BundleAndVfx = new HashSet<BundleAndVfx>();
            BundleAndVoiceFilter = new HashSet<BundleAndVoiceFilter>();
            BundleAndWardrobe = new HashSet<BundleAndWardrobe>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long ReadinessId { get; set; }
        public DateTime CreatedTime { get; set; }
        public long[] Tags { get; set; }

        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual ICollection<AccountTransactionAndBundle> AccountTransactionAndBundle { get; set; }
        public virtual ICollection<BundleAndAutoclip> BundleAndAutoclip { get; set; }
        public virtual ICollection<BundleAndBodyAnimation> BundleAndBodyAnimation { get; set; }
        public virtual ICollection<BundleAndCameraFilter> BundleAndCameraFilter { get; set; }
        public virtual ICollection<BundleAndCharacter> BundleAndCharacter { get; set; }
        public virtual ICollection<BundleAndProp> BundleAndProp { get; set; }
        public virtual ICollection<BundleAndScore> BundleAndScore { get; set; }
        public virtual ICollection<BundleAndSetLocation> BundleAndSetLocation { get; set; }
        public virtual ICollection<BundleAndSong> BundleAndSong { get; set; }
        public virtual ICollection<BundleAndSticker> BundleAndSticker { get; set; }
        public virtual ICollection<BundleAndVfx> BundleAndVfx { get; set; }
        public virtual ICollection<BundleAndVoiceFilter> BundleAndVoiceFilter { get; set; }
        public virtual ICollection<BundleAndWardrobe> BundleAndWardrobe { get; set; }
    }
}