// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CameraAnimation
    {
        public CameraAnimation()
        {
            CameraAnimationTemplate = new HashSet<CameraAnimationTemplate>();
            CameraController = new HashSet<CameraController>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public string FilesInfo { get; set; }

        public virtual Group Group { get; set; }
        public virtual ICollection<CameraAnimationTemplate> CameraAnimationTemplate { get; set; }
        public virtual ICollection<CameraController> CameraController { get; set; }
    }
}