// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CameraFilterCategory
    {
        public CameraFilterCategory()
        {
            BrandAndCameraFilterCategory = new HashSet<BrandAndCameraFilterCategory>();
            CameraFilter = new HashSet<CameraFilter>();
            SetLocationCategoryAndCameraFilterCategory = new HashSet<SetLocationCategoryAndCameraFilterCategory>();
            SetLocationMoodAndCameraFilterCategory = new HashSet<SetLocationMoodAndCameraFilterCategory>();
            WardrobeCollectionAndCameraFilterCategory = new HashSet<WardrobeCollectionAndCameraFilterCategory>();
            WardrobeStyleAndCameraFilterCategory = new HashSet<WardrobeStyleAndCameraFilterCategory>();
            CameraFilterSubCategory = new HashSet<CameraFilterSubCategory>();
        }

        public long Id { get; set; } 
        public string Name { get; set; }
        public int SortOrder { get; set; }

        public virtual ICollection<BrandAndCameraFilterCategory> BrandAndCameraFilterCategory { get; set; }
        public virtual ICollection<CameraFilter> CameraFilter { get; set; }
        public virtual ICollection<SetLocationCategoryAndCameraFilterCategory> SetLocationCategoryAndCameraFilterCategory { get; set; }
        public virtual ICollection<SetLocationMoodAndCameraFilterCategory> SetLocationMoodAndCameraFilterCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndCameraFilterCategory> WardrobeCollectionAndCameraFilterCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndCameraFilterCategory> WardrobeStyleAndCameraFilterCategory { get; set; }
        public virtual ICollection<CameraFilterSubCategory> CameraFilterSubCategory { get; set; }
    }
}