// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CameraAnimationTemplate
    {
        public CameraAnimationTemplate()
        {
            CameraController = new HashSet<CameraController>();
            QaComments = new HashSet<QaComments>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public string DisplayName { get; set; }
        public long CameraCategoryId { get; set; }
        public long CameraAnimationTypeId { get; set; }
        public long? Size { get; set; }
        public long ReadinessId { get; set; }
        public long UploaderUserId { get; set; }
        public string FilesInfo { get; set; }
        public bool IsDefault { get; set; }
        public long CameraAnimationId { get; set; }
        public int SortOrder { get; set; }

        public virtual CameraAnimation CameraAnimation { get; set; }
        public virtual CameraAnimationType CameraAnimationType { get; set; }
        public virtual CameraCategory CameraCategory { get; set; }
        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual ICollection<CameraController> CameraController { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
    }
}