// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CameraCategory
    {
        public CameraCategory()
        {
            CameraAnimationTemplate = new HashSet<CameraAnimationTemplate>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }

        public virtual ICollection<CameraAnimationTemplate> CameraAnimationTemplate { get; set; }
    }
}