// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CampaignAndUser
    {
        public long CampaignId { get; set; }
        public long UserId { get; set; }

        public virtual Campaign Campaign { get; set; }
        public virtual User User { get; set; }
    }
}