// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CharacterControllerUmaRecipe
    {
        public long Id { get; set; }
        public long CharacterControllerId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public long? UmaRecipeId { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }

        public virtual CharacterController CharacterController { get; set; }
        public virtual UmaRecipe UmaRecipe { get; set; }
    }
}