// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CharacterControllerBackgroundDancer
    {
        public long CharacterControllerId { get; set; }
        public long UmaRecipeId { get; set; }
        public long PrimaryBodyAnimationId { get; set; }
        public long? LowerBodyAnimationId { get; set; }
        public long? FaceAnimation { get; set; }
        public long ControllerSequenceNumber { get; set; }
        public long CharacterId { get; set; }

        public virtual Character Character { get; set; }
        public virtual CharacterController CharacterController { get; set; }
        public virtual FaceAnimation FaceAnimationNavigation { get; set; }
        public virtual AsseManager.BodyAnimation LowerBodyAnimation { get; set; }
        public virtual AsseManager.BodyAnimation PrimaryBodyAnimation { get; set; }
        public virtual UmaRecipe UmaRecipe { get; set; }
    }
}