// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CharacterControllerFaceVoice
    {
        public long Id { get; set; }
        public long CharacterControllerId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public long? VoiceTrackId { get; set; }
        public long? FaceAnimationId { get; set; }
        public long? VoiceFilterId { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }
        public long? ExtremeExpressionId { get; set; }
        public long? FaceVfxId { get; set; }
        public int VoiceSoundVolume { get; set; }
        public int? VoiceFilterValue { get; set; }

        public virtual CharacterController CharacterController { get; set; }
        public virtual ExtremeExpression ExtremeExpression { get; set; }
        public virtual FaceAnimation FaceAnimation { get; set; }
        public virtual Vfx FaceVfx { get; set; }
        public virtual VoiceFilter VoiceFilter { get; set; }
        public virtual VoiceTrack VoiceTrack { get; set; }
    }
}