// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CharacterSpawnPositionFormation
    {
        public CharacterSpawnPositionFormation()
        {
            CharacterSpawnPositionAndFormation = new HashSet<CharacterSpawnPositionAndFormation>();
            Event = new HashSet<Event>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public int CharacterCount { get; set; }
        public int SortOrder { get; set; }
        public long CharacterSpawnPositionFormationTypeId { get; set; }
        public string FilesInfo { get; set; }

        public virtual CharacterSpawnPositionFormationType CharacterSpawnPositionFormationType { get; set; }
        public virtual ICollection<CharacterSpawnPositionAndFormation> CharacterSpawnPositionAndFormation { get; set; }
        public virtual ICollection<Event> Event { get; set; }
    }
}