// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class ControllerTypeAndLevelTemplate
    {
        public long LevelTemplateId { get; set; }
        public long ControllerTypeId { get; set; }
        public int ControllerSequence { get; set; }

        public virtual ControllerType ControllerType { get; set; }
        public virtual LevelTemplate LevelTemplate { get; set; }
    }
}