// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class ControllerType
    {
        public ControllerType()
        {
            ControllerTypeAndLevelTemplate = new HashSet<ControllerTypeAndLevelTemplate>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<ControllerTypeAndLevelTemplate> ControllerTypeAndLevelTemplate { get; set; }
    }
}