// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Country
    {
        public Country()
        {
            Group = new HashSet<Group>();
        }

        public long Id { get; set; }
        public string Isoname { get; set; }
        public string DisplayName { get; set; }

        public virtual ICollection<Group> Group { get; set; }
    }
}