// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class CreatorSource
    {
        public CreatorSource()
        {
            AssetStoreInfo = new HashSet<AssetStoreInfo>();
            EventSpecialAssetbundle = new HashSet<EventSpecialAssetbundle>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<AssetStoreInfo> AssetStoreInfo { get; set; }
        public virtual ICollection<EventSpecialAssetbundle> EventSpecialAssetbundle { get; set; }
    }
}