// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Currency
    {
        public Currency()
        {
            DepositBlock = new HashSet<DepositBlock>();
            ExchangeTransaction = new HashSet<ExchangeTransaction>();
            Group = new HashSet<Group>();
            WithdrawalBlock = new HashSet<WithdrawalBlock>();
        }

        public long Id { get; set; }
        public string Isoname { get; set; }
        public string DisplayName { get; set; }
        public string Symbol { get; set; }

        public virtual ICollection<DepositBlock> DepositBlock { get; set; }
        public virtual ICollection<ExchangeTransaction> ExchangeTransaction { get; set; }
        public virtual ICollection<Group> Group { get; set; }
        public virtual ICollection<WithdrawalBlock> WithdrawalBlock { get; set; }
    }
}