// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Event
    {
       public Event()
        {
            CameraController = new HashSet<CameraController>();
            CameraFilterController = new HashSet<CameraFilterController>();
            CharacterController = new HashSet<CharacterController>();
            EventAndEventSpecialAssetbundle = new HashSet<EventAndEventSpecialAssetbundle>();
            MusicController = new HashSet<MusicController>();
            PropController = new HashSet<PropController>();
            SetLocationController = new HashSet<SetLocationController>();
            SfxController = new HashSet<SfxController>();
            StickerController = new HashSet<StickerController>();
            VfxController = new HashSet<VfxController>();
            Caption = new HashSet<Caption>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long LevelId { get; set; }
        public int LevelSequence { get; set; }
        public long? AutoclipId { get; set; }
        public int TargetCharacterSequenceNumber { get; set; }
        public string FilesInfo { get; set; }
        public int Length { get; set; }
        public long CharacterSpawnPositionId { get; set; }
        public long? CharacterSpawnPositionFormationId { get; set; }
        public long? TemplateId { get; set; }

        public virtual Autoclip Autoclip { get; set; }
        public virtual CharacterSpawnPosition CharacterSpawnPosition { get; set; }
        public virtual CharacterSpawnPositionFormation CharacterSpawnPositionFormation { get; set; }
        public virtual Group Group { get; set; }
        public virtual Level Level { get; set; }
        public virtual ICollection<CameraController> CameraController { get; set; }
        public virtual ICollection<CameraFilterController> CameraFilterController { get; set; }
        public virtual ICollection<Caption> Caption { get; set; }
        public virtual ICollection<CharacterController> CharacterController { get; set; }
        public virtual ICollection<EventAndEventSpecialAssetbundle> EventAndEventSpecialAssetbundle { get; set; }
        public virtual ICollection<MusicController> MusicController { get; set; }
        public virtual ICollection<PropController> PropController { get; set; }
        public virtual ICollection<SetLocationController> SetLocationController { get; set; }
        public virtual ICollection<SfxController> SfxController { get; set; }
        public virtual ICollection<StickerController> StickerController { get; set; }
        public virtual ICollection<VfxController> VfxController { get; set; }
    }
}