// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class EventSpecialAssetbundle
    {
        public EventSpecialAssetbundle()
        {
            EventAndEventSpecialAssetbundle = new HashSet<EventAndEventSpecialAssetbundle>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public string DisplayName { get; set; }
        public int[] DescriptionKeywords { get; set; }
        public long CreatorSourceId { get; set; }

        public virtual CreatorSource CreatorSource { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<EventAndEventSpecialAssetbundle> EventAndEventSpecialAssetbundle { get; set; }
    }
}