// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class ExchangeTransaction
    {
        public long Id { get; set; }
        public long CurrencyId { get; set; }
        public decimal Amount { get; set; }
        public decimal PaymentFee { get; set; }
        public long PaymentSystemId { get; set; }
        public string PaymentInformation { get; set; }

        public virtual Currency Currency { get; set; }
        public virtual AccountTransaction IdNavigation { get; set; }
        public virtual PaymentSystem PaymentSystem { get; set; }
    }
}