// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class ExtremeExpression
    {
        public ExtremeExpression()
        {
            CharacterControllerFaceVoice = new HashSet<CharacterControllerFaceVoice>();
            QaComments = new HashSet<QaComments>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long ExtremeExpressionBundleId { get; set; }
        public int ExtremeExpressionIndex { get; set; }
        public long ReadinessId { get; set; }

        public virtual ExtremeExpressionBundle ExtremeExpressionBundle { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual ICollection<CharacterControllerFaceVoice> CharacterControllerFaceVoice { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
    }
}