// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class FaceAnimation
    {
        public FaceAnimation()
        {
            CharacterControllerBackgroundDancer = new HashSet<CharacterControllerBackgroundDancer>();
            CharacterControllerFaceVoice = new HashSet<CharacterControllerFaceVoice>();
            QaComments = new HashSet<QaComments>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long GroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long FaceAnimationCategoryId { get; set; }
        public long? Size { get; set; }
        public int? Duration { get; set; }
        public int? FrameRate { get; set; }
        public int? MusicStartCue { get; set; }
        public long UploaderUserId { get; set; }
        public long[] Tags { get; set; }
        public string FilesInfo { get; set; }

        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual FaceAnimationCategory FaceAnimationCategory { get; set; }
        public virtual Group Group { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual ICollection<CharacterControllerBackgroundDancer> CharacterControllerBackgroundDancer { get; set; }
        public virtual ICollection<CharacterControllerFaceVoice> CharacterControllerFaceVoice { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
    }
}