// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Gender
    {
        public Gender()
        {
            Character = new HashSet<Character>();
            Group = new HashSet<Group>();
            Wardrobe = new HashSet<Wardrobe>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long RaceId { get; set; }

        public virtual ICollection<Character> Character { get; set; }
        public virtual ICollection<Group> Group { get; set; }
        public virtual ICollection<Wardrobe> Wardrobe { get; set; }
    }
}