// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class GroupAndScore
    {
        public long GroupId { get; set; }
        public long ScoreId { get; set; }
        public DateTime PurchaseTime { get; set; }
        public bool IsWishlistItem { get; set; }
        public long? PriceruleAppliedId { get; set; }

        public virtual Group Group { get; set; }
        public virtual Pricerule PriceruleApplied { get; set; }
        public virtual Score Score { get; set; }
    }
}