// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Group
    {
       public Group()
        {
            Autoclip = new HashSet<Autoclip>();
            AwardedBadge = new HashSet<AwardedBadge>();
            BodyAnimation = new HashSet<AsseManager.BodyAnimation>();
            Brand = new HashSet<Brand>();
            CameraAnimation = new HashSet<CameraAnimation>();
            CameraAnimationTemplate = new HashSet<CameraAnimationTemplate>();
            CameraAnimationType = new HashSet<CameraAnimationType>();
            CameraFilter = new HashSet<CameraFilter>();
            Campaign = new HashSet<Campaign>();
            CampaignAndGroup = new HashSet<CampaignAndGroup>();
            CampaignFulfillment = new HashSet<CampaignFulfillment>();
            Character = new HashSet<Character>();
            CharacterGroupPermission = new HashSet<CharacterGroupPermission>();
            CharacterSpawnPosition = new HashSet<CharacterSpawnPosition>();
            Crowd = new HashSet<Crowd>();
            CrowdMovement = new HashSet<CrowdMovement>();
            Event = new HashSet<Event>();
            EventSpecialAssetbundle = new HashSet<EventSpecialAssetbundle>();
            ExtremeExpressionBundle = new HashSet<ExtremeExpressionBundle>();
            FaceAnimation = new HashSet<FaceAnimation>();
            FollowerFollowerNavigation = new HashSet<Follower>();
            FollowerFollowing = new HashSet<Follower>();
            FollowerHistoryFollower = new HashSet<FollowerHistory>();
            FollowerHistoryFollowing = new HashSet<FollowerHistory>();
            GroupAndAutoclip = new HashSet<GroupAndAutoclip>();
            GroupAndBodyAnimation = new HashSet<GroupAndBodyAnimation>();
            GroupAndCameraFilter = new HashSet<GroupAndCameraFilter>();
            GroupAndCharacter = new HashSet<GroupAndCharacter>();
            GroupAndLevel = new HashSet<GroupAndLevel>();
            GroupAndProp = new HashSet<GroupAndProp>();
            GroupAndScore = new HashSet<GroupAndScore>();
            GroupAndSetLocation = new HashSet<GroupAndSetLocation>();
            GroupAndSong = new HashSet<GroupAndSong>();
            GroupAndSticker = new HashSet<GroupAndSticker>();
            GroupAndVfx = new HashSet<GroupAndVfx>();
            GroupAndVoiceFilter = new HashSet<GroupAndVoiceFilter>();
            GroupAndWardrobe = new HashSet<GroupAndWardrobe>();
            LevelGroup = new HashSet<Level>();
            LevelOriginalGroup = new HashSet<Level>();
            Outfit = new HashSet<Outfit>();
            PayoutContract = new HashSet<PayoutContract>();
            Photo = new HashSet<Photo>();
            PriceruleAndGroup = new HashSet<PriceruleAndGroup>();
            Prop = new HashSet<Prop>();
            Score = new HashSet<Score>();
            SetLocation = new HashSet<SetLocation>();
            SetLocationBundle = new HashSet<SetLocationBundle>();
            Sfx = new HashSet<Sfx>();
            Song = new HashSet<Song>();
            Sticker = new HashSet<Sticker>();
            UmaBundle = new HashSet<UmaBundle>();
            User = new HashSet<User>();
            UserAndGroup = new HashSet<UserAndGroup>();
            UserSound = new HashSet<UserSound>();
            Vfx = new HashSet<Vfx>();
            VideoClip = new HashSet<VideoClip>();
            VoiceFilter = new HashSet<VoiceFilter>();
            VoiceTrack = new HashSet<VoiceTrack>();
            Wardrobe = new HashSet<Wardrobe>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public bool IsPrimary { get; set; }
        public long ManagerId { get; set; }
        public long? CurrencyId { get; set; }
        public long? TaxationCountryId { get; set; }
        public DateTime CreatedTime { get; set; }
        public bool Private { get; set; }
        public int NumberOfLevels { get; set; }
        public int FanLevel { get; set; }
        public int CreatorLevel { get; set; }
        public bool VerifiedGroup { get; set; }
        public int PremiumLevel { get; set; }
        public DateTime? BirthDate { get; set; }
        public long? Gender { get; set; }
        public long? ToplistPosition { get; set; }
        public bool IsBlocked { get; set; }
        public bool SavedOnlyBdayYear { get; set; }
        public DateTime? DeletedAt { get; set; }
        
        public virtual Currency Currency { get; set; }
        public virtual Gender GenderNavigation { get; set; }
        public virtual User Manager { get; set; }
        public virtual Country TaxationCountry { get; set; }
        public virtual AccountBalance AccountBalance { get; set; }
        public virtual TopGroups TopGroups { get; set; }
        public virtual ICollection<Autoclip> Autoclip { get; set; }
        public virtual ICollection<AwardedBadge> AwardedBadge { get; set; }
        public virtual ICollection<AsseManager.BodyAnimation> BodyAnimation { get; set; }
        public virtual ICollection<Brand> Brand { get; set; }
        public virtual ICollection<CameraAnimation> CameraAnimation { get; set; }
        public virtual ICollection<CameraAnimationTemplate> CameraAnimationTemplate { get; set; }
        public virtual ICollection<CameraAnimationType> CameraAnimationType { get; set; }
        public virtual ICollection<CameraFilter> CameraFilter { get; set; }
        public virtual ICollection<Campaign> Campaign { get; set; }
        public virtual ICollection<CampaignAndGroup> CampaignAndGroup { get; set; }
        public virtual ICollection<CampaignFulfillment> CampaignFulfillment { get; set; }
        public virtual ICollection<Character> Character { get; set; }
        public virtual ICollection<CharacterGroupPermission> CharacterGroupPermission { get; set; }
        public virtual ICollection<CharacterSpawnPosition> CharacterSpawnPosition { get; set; }
        public virtual ICollection<Crowd> Crowd { get; set; }
        public virtual ICollection<CrowdMovement> CrowdMovement { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<EventSpecialAssetbundle> EventSpecialAssetbundle { get; set; }
        public virtual ICollection<ExtremeExpressionBundle> ExtremeExpressionBundle { get; set; }
        public virtual ICollection<FaceAnimation> FaceAnimation { get; set; }
        public virtual ICollection<Follower> FollowerFollowerNavigation { get; set; }
        public virtual ICollection<Follower> FollowerFollowing { get; set; }
        public virtual ICollection<FollowerHistory> FollowerHistoryFollower { get; set; }
        public virtual ICollection<FollowerHistory> FollowerHistoryFollowing { get; set; }
        public virtual ICollection<GroupAndAutoclip> GroupAndAutoclip { get; set; }
        public virtual ICollection<GroupAndBodyAnimation> GroupAndBodyAnimation { get; set; }
        public virtual ICollection<GroupAndCameraFilter> GroupAndCameraFilter { get; set; }
        public virtual ICollection<GroupAndCharacter> GroupAndCharacter { get; set; }
        public virtual ICollection<GroupAndLevel> GroupAndLevel { get; set; }
        public virtual ICollection<GroupAndProp> GroupAndProp { get; set; }
        public virtual ICollection<GroupAndScore> GroupAndScore { get; set; }
        public virtual ICollection<GroupAndSetLocation> GroupAndSetLocation { get; set; }
        public virtual ICollection<GroupAndSong> GroupAndSong { get; set; }
        public virtual ICollection<GroupAndSticker> GroupAndSticker { get; set; }
        public virtual ICollection<GroupAndVfx> GroupAndVfx { get; set; }
        public virtual ICollection<GroupAndVoiceFilter> GroupAndVoiceFilter { get; set; }
        public virtual ICollection<GroupAndWardrobe> GroupAndWardrobe { get; set; }
        public virtual ICollection<Level> LevelGroup { get; set; }
        public virtual ICollection<Level> LevelOriginalGroup { get; set; }
        public virtual ICollection<Outfit> Outfit { get; set; }
        public virtual ICollection<PayoutContract> PayoutContract { get; set; }
        public virtual ICollection<Photo> Photo { get; set; }
        public virtual ICollection<PriceruleAndGroup> PriceruleAndGroup { get; set; }
        public virtual ICollection<Prop> Prop { get; set; }
        public virtual ICollection<Score> Score { get; set; }
        public virtual ICollection<SetLocation> SetLocation { get; set; }
        public virtual ICollection<SetLocationBundle> SetLocationBundle { get; set; }
        public virtual ICollection<Sfx> Sfx { get; set; }
        public virtual ICollection<Song> Song { get; set; }
        public virtual ICollection<Sticker> Sticker { get; set; }
        public virtual ICollection<UmaBundle> UmaBundle { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<UserAndGroup> UserAndGroup { get; set; }
        public virtual ICollection<UserSound> UserSound { get; set; }
        public virtual ICollection<Vfx> Vfx { get; set; }
        public virtual ICollection<VideoClip> VideoClip { get; set; }
        public virtual ICollection<VoiceFilter> VoiceFilter { get; set; }
        public virtual ICollection<VoiceTrack> VoiceTrack { get; set; }
        public virtual ICollection<Wardrobe> Wardrobe { get; set; }
    }
}