// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class LevelAndHashtag
    {
        public long LevelId { get; set; }
        public long HashtagId { get; set; }

        public virtual Hashtag Hashtag { get; set; }
        public virtual Level Level { get; set; }
    }
}