// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class LevelAbuseResult
    {
        public LevelAbuseResult()
        {
            LevelAbuseReport = new HashSet<LevelAbuseReport>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<LevelAbuseReport> LevelAbuseReport { get; set; }
    }
}