// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class LevelTemplate
    {
        public LevelTemplate()
        {
            ControllerTypeAndLevelTemplate = new HashSet<ControllerTypeAndLevelTemplate>();
            Level = new HashSet<Level>();
            LevelTemplateAndAutoclip = new HashSet<LevelTemplateAndAutoclip>();
            LevelTemplateAndBodyAnimation = new HashSet<LevelTemplateAndBodyAnimation>();
            LevelTemplateAndProp = new HashSet<LevelTemplateAndProp>();
            LevelTemplateAndSetLocation = new HashSet<LevelTemplateAndSetLocation>();
            LevelTemplateAndVfx = new HashSet<LevelTemplateAndVfx>();
        }

        public long Id { get; set; }
        public long LevelTypeId { get; set; }
        public string Name { get; set; }
        public bool BodyAnimationLocomotionAllowed { get; set; }
        public bool BodyAnimationLoopingAllowed { get; set; }
        public bool VfxLoopingAllowed { get; set; }
        public bool AutoclipAllowed { get; set; }
        public bool MidEventDeletable { get; set; }

        public virtual LevelType LevelType { get; set; }
        public virtual ICollection<ControllerTypeAndLevelTemplate> ControllerTypeAndLevelTemplate { get; set; }
        public virtual ICollection<Level> Level { get; set; }
        public virtual ICollection<LevelTemplateAndAutoclip> LevelTemplateAndAutoclip { get; set; }
        public virtual ICollection<LevelTemplateAndBodyAnimation> LevelTemplateAndBodyAnimation { get; set; }
        public virtual ICollection<LevelTemplateAndProp> LevelTemplateAndProp { get; set; }
        public virtual ICollection<LevelTemplateAndSetLocation> LevelTemplateAndSetLocation { get; set; }
        public virtual ICollection<LevelTemplateAndVfx> LevelTemplateAndVfx { get; set; }
    }
}