// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class LevelType
    {
        public LevelType()
        {
            LevelTemplate = new HashSet<LevelTemplate>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<LevelTemplate> LevelTemplate { get; set; }
    }
}