// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class LevelAbuseReport
    {
        public long Id { get; set; }
        public long LevelId { get; set; }
        public long UserId { get; set; }
        public DateTime ReportedAt { get; set; }
        public long? AssignedToUserId { get; set; }
        public long? ClosedResult { get; set; }
        public DateTime? ClosedAt { get; set; }
        public string ReporterComment { get; set; }
        public string ResolverComment { get; set; }

        public virtual User AssignedToUser { get; set; }
        public virtual LevelAbuseResult ClosedResultNavigation { get; set; }
        public virtual Level Level { get; set; }
        public virtual User User { get; set; }
    }
}