// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class LevelTemplateAndProp
    {
        public long LevelTemplateId { get; set; }
        public long PropId { get; set; }

        public virtual LevelTemplate LevelTemplate { get; set; }
        public virtual Prop Prop { get; set; }
    }
}