// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class LightSettings
    {
        public long Id { get; set; }
        public string Color { get; set; }
        public int Intensity { get; set; }
        public long CharacterSpawnPositionId { get; set; }
        public Guid UnityGuid { get; set; }
        public Guid GlobalId { get; set; }

        public virtual CharacterSpawnPosition CharacterSpawnPosition { get; set; }
    }
}