// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class MultiLanguageLevel
    {
        public MultiLanguageLevel()
        {
            LevelAndMultiLanguageLevel = new HashSet<LevelAndMultiLanguageLevel>();
        }

        public long Id { get; set; }

        public virtual ICollection<LevelAndMultiLanguageLevel> LevelAndMultiLanguageLevel { get; set; }
    }
}