// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class MusicController
    {
        public long Id { get; set; }
        public long EventId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public long? SongId { get; set; }
        public long? ScoreId { get; set; }
        public long? UserSoundId { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }
        public int LevelSoundVolume { get; set; }

        public virtual Event Event { get; set; }
        public virtual Score Score { get; set; }
        public virtual Song Song { get; set; }
        public virtual UserSound UserSound { get; set; }
    }
}