// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Notification
    {
        public Notification()
        {
            NotificationAndUser = new HashSet<NotificationAndUser>();
        }

        public long Id { get; set; }
        public DateTime TimeStamp { get; set; }
        public DateTime Expires { get; set; }
        public bool DeleteOnRead { get; set; }
        public string Message { get; set; }
        public string Link { get; set; }

        public virtual ICollection<NotificationAndUser> NotificationAndUser { get; set; }
    }
}