// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class NotificationAndUser
    {
        public long NotificationId { get; set; }
        public long UserId { get; set; }

        public virtual Notification Notification { get; set; }
        public virtual User User { get; set; }
    }
}