// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Outfit
    {
        public Outfit()
        {
            Character = new HashSet<Character>();
            OutfitAndWardrobe = new HashSet<OutfitAndWardrobe>();
            OutfitAndUmaSharedColor = new HashSet<OutfitAndUmaSharedColor>();
            CharacterController = new HashSet<CharacterController>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long ReadinessId { get; set; }
        public DateTime CreatedTime { get; set; }
        public string Name { get; set; }
        public long GroupId { get; set; }
        public long[] Tags { get; set; }
        public string FilesInfo { get; set; }
        public int SortOrder { get; set; }

        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual ICollection<Character> Character { get; set; }
        public virtual ICollection<CharacterController> CharacterController { get; set; }
        public virtual ICollection<OutfitAndWardrobe> OutfitAndWardrobe { get; set; }
        public virtual ICollection<OutfitAndUmaSharedColor> OutfitAndUmaSharedColor { get; set; }
    }
}