// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class PayoutContract
    {
        public PayoutContract()
        {
            AssetStoreInfo = new HashSet<AssetStoreInfo>();
        }

        public long Id { get; set; }
        public long GroupId { get; set; }
        public long PayoutSchemeId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime? ValidUntil { get; set; }
        public DateTime? LastCalculated { get; set; }

        public virtual Group Group { get; set; }
        public virtual PayoutScheme PayoutScheme { get; set; }
        public virtual ICollection<AssetStoreInfo> AssetStoreInfo { get; set; }
    }
}