// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Pipeline
    {
        public Pipeline()
        {
            DeviceTypeAndPipeline = new HashSet<DeviceTypeAndPipeline>();
            SetLocation = new HashSet<SetLocation>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<DeviceTypeAndPipeline> DeviceTypeAndPipeline { get; set; }
        public virtual ICollection<SetLocation> SetLocation { get; set; }
    }
}