// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Bridge.Models.AsseManager
{
    public partial class Pricerule
    {
        public Pricerule()
        {
            GroupAndAutoclip = new HashSet<GroupAndAutoclip>();
            GroupAndBodyAnimation = new HashSet<GroupAndBodyAnimation>();
            GroupAndCameraFilter = new HashSet<GroupAndCameraFilter>();
            GroupAndCharacter = new HashSet<GroupAndCharacter>();
            GroupAndProp = new HashSet<GroupAndProp>();
            GroupAndScore = new HashSet<GroupAndScore>();
            GroupAndSetLocation = new HashSet<GroupAndSetLocation>();
            GroupAndSong = new HashSet<GroupAndSong>();
            GroupAndSticker = new HashSet<GroupAndSticker>();
            GroupAndVfx = new HashSet<GroupAndVfx>();
            GroupAndVoiceFilter = new HashSet<GroupAndVoiceFilter>();
            GroupAndWardrobe = new HashSet<GroupAndWardrobe>();
            PriceruleAndAutoclip = new HashSet<PriceruleAndAutoclip>();
            PriceruleAndBodyAnimation = new HashSet<PriceruleAndBodyAnimation>();
            PriceruleAndCameraFilter = new HashSet<PriceruleAndCameraFilter>();
            PriceruleAndCharacter = new HashSet<PriceruleAndCharacter>();
            PriceruleAndDeviceType = new HashSet<PriceruleAndDeviceType>();
            PriceruleAndGroup = new HashSet<PriceruleAndGroup>();
            PriceruleAndProp = new HashSet<PriceruleAndProp>();
            PriceruleAndScore = new HashSet<PriceruleAndScore>();
            PriceruleAndSetLocation = new HashSet<PriceruleAndSetLocation>();
            PriceruleAndSong = new HashSet<PriceruleAndSong>();
            PriceruleAndSticker = new HashSet<PriceruleAndSticker>();
            PriceruleAndTeam = new HashSet<PriceruleAndTeam>();
            PriceruleAndUser = new HashSet<PriceruleAndUser>();
            PriceruleAndVerticalCategory = new HashSet<PriceruleAndVerticalCategory>();
            PriceruleAndVfx = new HashSet<PriceruleAndVfx>();
            PriceruleAndVoiceFilter = new HashSet<PriceruleAndVoiceFilter>();
            PriceruleAndWardrobe = new HashSet<PriceruleAndWardrobe>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public DateTime ValidDuring { get; set; }
        public string Rules { get; set; }

        public virtual ICollection<GroupAndAutoclip> GroupAndAutoclip { get; set; }
        public virtual ICollection<GroupAndBodyAnimation> GroupAndBodyAnimation { get; set; }
        public virtual ICollection<GroupAndCameraFilter> GroupAndCameraFilter { get; set; }
        public virtual ICollection<GroupAndCharacter> GroupAndCharacter { get; set; }
        public virtual ICollection<GroupAndProp> GroupAndProp { get; set; }
        public virtual ICollection<GroupAndScore> GroupAndScore { get; set; }
        public virtual ICollection<GroupAndSetLocation> GroupAndSetLocation { get; set; }
        public virtual ICollection<GroupAndSong> GroupAndSong { get; set; }
        public virtual ICollection<GroupAndSticker> GroupAndSticker { get; set; }
        public virtual ICollection<GroupAndVfx> GroupAndVfx { get; set; }
        public virtual ICollection<GroupAndVoiceFilter> GroupAndVoiceFilter { get; set; }
        public virtual ICollection<GroupAndWardrobe> GroupAndWardrobe { get; set; }
        public virtual ICollection<PriceruleAndAutoclip> PriceruleAndAutoclip { get; set; }
        public virtual ICollection<PriceruleAndBodyAnimation> PriceruleAndBodyAnimation { get; set; }
        public virtual ICollection<PriceruleAndCameraFilter> PriceruleAndCameraFilter { get; set; }
        public virtual ICollection<PriceruleAndCharacter> PriceruleAndCharacter { get; set; }
        public virtual ICollection<PriceruleAndDeviceType> PriceruleAndDeviceType { get; set; }
        public virtual ICollection<PriceruleAndGroup> PriceruleAndGroup { get; set; }
        public virtual ICollection<PriceruleAndProp> PriceruleAndProp { get; set; }
        public virtual ICollection<PriceruleAndScore> PriceruleAndScore { get; set; }
        public virtual ICollection<PriceruleAndSetLocation> PriceruleAndSetLocation { get; set; }
        public virtual ICollection<PriceruleAndSong> PriceruleAndSong { get; set; }
        public virtual ICollection<PriceruleAndSticker> PriceruleAndSticker { get; set; }
        public virtual ICollection<PriceruleAndTeam> PriceruleAndTeam { get; set; }
        public virtual ICollection<PriceruleAndUser> PriceruleAndUser { get; set; }
        public virtual ICollection<PriceruleAndVerticalCategory> PriceruleAndVerticalCategory { get; set; }
        public virtual ICollection<PriceruleAndVfx> PriceruleAndVfx { get; set; }
        public virtual ICollection<PriceruleAndVoiceFilter> PriceruleAndVoiceFilter { get; set; }
        public virtual ICollection<PriceruleAndWardrobe> PriceruleAndWardrobe { get; set; }
    }
}