// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class PriceruleAndVfx
    {
        public long PriceruleId { get; set; }
        public long VfxId { get; set; }

        public virtual Pricerule Pricerule { get; set; }
        public virtual Vfx Vfx { get; set; }
    }
}