// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class PropController
    {
        public long Id { get; set; }
        public long EventId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public long? PropId { get; set; }
        public long? BodyAnimationId { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }
        public bool Locomotion { get; set; }

        public virtual AsseManager.BodyAnimation BodyAnimation { get; set; }
        public virtual Event Event { get; set; }
        public virtual Prop Prop { get; set; }
    }
}