// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class PropSubCategory
    {
        public PropSubCategory()
        {
            Prop = new HashSet<Prop>();
        }

        public long Id { get; set; }
        public long PropCategoryId { get; set; }
        public string Name { get; set; }

        public virtual PropCategory PropCategory { get; set; }
        public virtual ICollection<Prop> Prop { get; set; }
    }
}