// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class QaComments
    {
        public long Id { get; set; }
        public long? SetLocationId { get; set; }
        public long? VfxId { get; set; }
        public long? VoiceFilterId { get; set; }
        public long? CharacterId { get; set; }
        public long? BodyAnimationId { get; set; }
        public long? FaceAnimationId { get; set; }
        public long? ScoreId { get; set; }
        public long? SongId { get; set; }
        public long? SfxId { get; set; }
        public long? CameraAnimationTemplateId { get; set; }
        public long? ExtremeExpressionId { get; set; }
        public long? CameraFilterId { get; set; }
        public long? AutoclipId { get; set; }
        public long? WardrobeId { get; set; }
        public long? PropId { get; set; }
        public long? StickerId { get; set; }
        public long CommentBy { get; set; }
        public DateTime CommentTime { get; set; }
        public long? ResolvedBy { get; set; }
        public DateTime? ResolvedTime { get; set; }
        public string Comment { get; set; }

        public virtual Autoclip Autoclip { get; set; }
        public virtual AsseManager.BodyAnimation BodyAnimation { get; set; }
        public virtual CameraAnimationTemplate CameraAnimationTemplate { get; set; }
        public virtual CameraFilter CameraFilter { get; set; }
        public virtual Character Character { get; set; }
        public virtual User CommentByNavigation { get; set; }
        public virtual ExtremeExpression ExtremeExpression { get; set; }
        public virtual FaceAnimation FaceAnimation { get; set; }
        public virtual Prop Prop { get; set; }
        public virtual User ResolvedByNavigation { get; set; }
        public virtual Score Score { get; set; }
        public virtual SetLocation SetLocation { get; set; }
        public virtual Sfx Sfx { get; set; }
        public virtual Song Song { get; set; }
        public virtual Sticker Sticker { get; set; }
        public virtual Vfx Vfx { get; set; }
        public virtual VoiceFilter VoiceFilter { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}