// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SeasonAndSetLocation
    {
        public long SeasonId { get; set; }
        public long SetLocationId { get; set; }

        public virtual Season Season { get; set; }
        public virtual SetLocation SetLocation { get; set; }
    }
}