// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SeasonAndCameraFilter
    {
        public long SeasonId { get; set; }
        public long CameraFilterId { get; set; }

        public virtual CameraFilter CameraFilter { get; set; }
        public virtual Season Season { get; set; }
    }
}