// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SeasonAndVoiceFilter
    {
        public long SeasonId { get; set; }
        public long VoiceFilterId { get; set; }

        public virtual Season Season { get; set; }
        public virtual VoiceFilter VoiceFilter { get; set; }
    }
}