// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationCategoryAndPropCategory
    {
        public long SetLocationCategoryId { get; set; }
        public long PropCategoryId { get; set; }
        public int SetLocationCategorySortKey { get; set; }
        public int PropCategorySortKey { get; set; }

        public virtual PropCategory PropCategory { get; set; }
        public virtual SetLocationCategory SetLocationCategory { get; set; }
    }
}