// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationController
    {
        public long Id { get; set; }
        public long EventId { get; set; }
        public int ControllerSequenceNumber { get; set; }
        public long SetLocationId { get; set; }
        public int ActivationCue { get; set; }
        public int EndCue { get; set; }
        public long? TimeOfDay { get; set; }
        public long WeatherId { get; set; }
        public long? CrowdId { get; set; }
        public long? CrowdMovementId { get; set; }
        public int? MaxCrowds { get; set; }
        public long? TimelapseSpeed { get; set; }
        public int? NpeAnimationSpeed { get; set; }
        public long? VideoClipId { get; set; }
        public long? PhotoId { get; set; }
        public int? VideoActivationCue { get; set; }
        public int? VideoEndCue { get; set; }
        public int VideoSoundVolume { get; set; }

        public virtual Crowd Crowd { get; set; }
        public virtual CrowdMovement CrowdMovement { get; set; }
        public virtual Event Event { get; set; }
        public virtual SetLocation SetLocation { get; set; }
        public virtual Weather Weather { get; set; }
        public virtual VideoClip VideoClip { get; set; }
        public virtual Photo Photo { get; set; }
    }
}