// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationBundle
    {
        public SetLocationBundle()
        {
            CharacterSpawnPosition = new HashSet<CharacterSpawnPosition>();
            SetLocation = new HashSet<SetLocation>();
            VfxSpawnPosition = new HashSet<VfxSpawnPosition>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long GroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public Guid UnityGuid { get; set; }
        public int PolyCount { get; set; }
        public long SizeKb { get; set; }
        public long ReadinessId { get; set; }
        public string FilesInfo { get; set; }

        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual ICollection<CharacterSpawnPosition> CharacterSpawnPosition { get; set; }
        public virtual ICollection<SetLocation> SetLocation { get; set; }
        public virtual ICollection<VfxSpawnPosition> VfxSpawnPosition { get; set; }
    }
}