// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationCategory
    {
        public SetLocationCategory()
        {
            BrandAndSetLocationCategory = new HashSet<BrandAndSetLocationCategory>();
            SetLocation = new HashSet<SetLocation>();
            SetLocationCategoryAndBodyAnimationCategory = new HashSet<SetLocationCategoryAndBodyAnimationCategory>();
            SetLocationCategoryAndCameraFilterCategory = new HashSet<SetLocationCategoryAndCameraFilterCategory>();
            SetLocationCategoryAndGenre = new HashSet<SetLocationCategoryAndGenre>();
            SetLocationCategoryAndPropCategory = new HashSet<SetLocationCategoryAndPropCategory>();
            SetLocationCategoryAndScoreCategory = new HashSet<SetLocationCategoryAndScoreCategory>();
            SetLocationCategoryAndSfxCategory = new HashSet<SetLocationCategoryAndSfxCategory>();
            SetLocationCategoryAndVfxCategory = new HashSet<SetLocationCategoryAndVfxCategory>();
            SetLocationSubCategory = new HashSet<SetLocationSubCategory>();
            WardrobeCollectionAndSetLocationCategory = new HashSet<WardrobeCollectionAndSetLocationCategory>();
            WardrobeStyleAndSetLocationCategory = new HashSet<WardrobeStyleAndSetLocationCategory>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }

        public virtual ICollection<BrandAndSetLocationCategory> BrandAndSetLocationCategory { get; set; }
        public virtual ICollection<SetLocation> SetLocation { get; set; }
        public virtual ICollection<SetLocationCategoryAndBodyAnimationCategory> SetLocationCategoryAndBodyAnimationCategory { get; set; }
        public virtual ICollection<SetLocationCategoryAndCameraFilterCategory> SetLocationCategoryAndCameraFilterCategory { get; set; }
        public virtual ICollection<SetLocationCategoryAndGenre> SetLocationCategoryAndGenre { get; set; }
        public virtual ICollection<SetLocationCategoryAndPropCategory> SetLocationCategoryAndPropCategory { get; set; }
        public virtual ICollection<SetLocationCategoryAndScoreCategory> SetLocationCategoryAndScoreCategory { get; set; }
        public virtual ICollection<SetLocationCategoryAndSfxCategory> SetLocationCategoryAndSfxCategory { get; set; }
        public virtual ICollection<SetLocationCategoryAndVfxCategory> SetLocationCategoryAndVfxCategory { get; set; }
        public virtual ICollection<SetLocationSubCategory> SetLocationSubCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndSetLocationCategory> WardrobeCollectionAndSetLocationCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndSetLocationCategory> WardrobeStyleAndSetLocationCategory { get; set; }
    }
}