// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationCategoryAndCameraFilterCategory
    {
        public long SetLocationCategoryId { get; set; }
        public long CameraFilterCategoryId { get; set; }
        public int SetLocationCategorySortKey { get; set; }
        public int CameraFilterCategorySortKey { get; set; }

        public virtual CameraFilterCategory CameraFilterCategory { get; set; }
        public virtual SetLocationCategory SetLocationCategory { get; set; }
    }
}