// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationMood
    {
        public SetLocationMood()
        {
            BrandAndSetLocationMood = new HashSet<BrandAndSetLocationMood>();
            SetLocation = new HashSet<SetLocation>();
            SetLocationMoodAndBodyAnimationCategory = new HashSet<SetLocationMoodAndBodyAnimationCategory>();
            SetLocationMoodAndCameraFilterCategory = new HashSet<SetLocationMoodAndCameraFilterCategory>();
            SetLocationMoodAndGenre = new HashSet<SetLocationMoodAndGenre>();
            SetLocationMoodAndPropCategory = new HashSet<SetLocationMoodAndPropCategory>();
            SetLocationMoodAndScoreCategory = new HashSet<SetLocationMoodAndScoreCategory>();
            SetLocationMoodAndSfxCategory = new HashSet<SetLocationMoodAndSfxCategory>();
            SetLocationMoodAndVfxCategory = new HashSet<SetLocationMoodAndVfxCategory>();
            WardrobeCollectionAndSetLocationMood = new HashSet<WardrobeCollectionAndSetLocationMood>();
            WardrobeStyleAndSetLocationMood = new HashSet<WardrobeStyleAndSetLocationMood>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<BrandAndSetLocationMood> BrandAndSetLocationMood { get; set; }
        public virtual ICollection<SetLocation> SetLocation { get; set; }
        public virtual ICollection<SetLocationMoodAndBodyAnimationCategory> SetLocationMoodAndBodyAnimationCategory { get; set; }
        public virtual ICollection<SetLocationMoodAndCameraFilterCategory> SetLocationMoodAndCameraFilterCategory { get; set; }
        public virtual ICollection<SetLocationMoodAndGenre> SetLocationMoodAndGenre { get; set; }
        public virtual ICollection<SetLocationMoodAndPropCategory> SetLocationMoodAndPropCategory { get; set; }
        public virtual ICollection<SetLocationMoodAndScoreCategory> SetLocationMoodAndScoreCategory { get; set; }
        public virtual ICollection<SetLocationMoodAndSfxCategory> SetLocationMoodAndSfxCategory { get; set; }
        public virtual ICollection<SetLocationMoodAndVfxCategory> SetLocationMoodAndVfxCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndSetLocationMood> WardrobeCollectionAndSetLocationMood { get; set; }
        public virtual ICollection<WardrobeStyleAndSetLocationMood> WardrobeStyleAndSetLocationMood { get; set; }
    }
}