// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SetLocationMoodAndVfxCategory
    {
        public long SetLocationMoodId { get; set; }
        public long VfxCategoryId { get; set; }
        public int SetLocationMoodSortKey { get; set; }
        public int VfxCategorySortKey { get; set; }

        public virtual SetLocationMood SetLocationMood { get; set; }
        public virtual VfxCategory VfxCategory { get; set; }
    }
}