// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Sfx
    {
        public Sfx()
        {
            QaComments = new HashSet<QaComments>();
            SfxController = new HashSet<SfxController>();
            WardrobeAndSfx = new HashSet<WardrobeAndSfx>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long SfxCategoryId { get; set; }
        public long GroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long ReadinessId { get; set; }
        public long? Size { get; set; }
        public int Channels { get; set; }
        public int SamplingSize { get; set; }
        public int Duration { get; set; }
        public int SamplingFrequency { get; set; }
        public string Name { get; set; }
        public long UploaderUserId { get; set; }
        public long[] Tags { get; set; }
        public string FilesInfo { get; set; }
        public int SortOrder { get; set; }

        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual SfxCategory SfxCategory { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
        public virtual ICollection<SfxController> SfxController { get; set; }
        public virtual ICollection<WardrobeAndSfx> WardrobeAndSfx { get; set; }
    }
}