// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class SfxCategory
    {
        public SfxCategory()
        {
            BrandAndSfxCategory = new HashSet<BrandAndSfxCategory>();
            SetLocationCategoryAndSfxCategory = new HashSet<SetLocationCategoryAndSfxCategory>();
            SetLocationMoodAndSfxCategory = new HashSet<SetLocationMoodAndSfxCategory>();
            Sfx = new HashSet<Sfx>();
            WardrobeCollectionAndSfxCategory = new HashSet<WardrobeCollectionAndSfxCategory>();
            WardrobeStyleAndSfxCategory = new HashSet<WardrobeStyleAndSfxCategory>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }

        public virtual ICollection<BrandAndSfxCategory> BrandAndSfxCategory { get; set; }
        public virtual ICollection<SetLocationCategoryAndSfxCategory> SetLocationCategoryAndSfxCategory { get; set; }
        public virtual ICollection<SetLocationMoodAndSfxCategory> SetLocationMoodAndSfxCategory { get; set; }
        public virtual ICollection<Sfx> Sfx { get; set; }
        public virtual ICollection<WardrobeCollectionAndSfxCategory> WardrobeCollectionAndSfxCategory { get; set; }
        public virtual ICollection<WardrobeStyleAndSfxCategory> WardrobeStyleAndSfxCategory { get; set; }
    }
}