// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Song
    {
        public Song()
        {
            AccountTransactionAndSong = new HashSet<AccountTransactionAndSong>();
            BodyAnimationAndSong = new HashSet<BodyAnimationAndSong>();
            BundleAndSong = new HashSet<BundleAndSong>();
            DeviceTypeAndSong = new HashSet<DeviceTypeAndSong>();
            GroupAndSong = new HashSet<GroupAndSong>();
            MusicController = new HashSet<MusicController>();
            PriceruleAndSong = new HashSet<PriceruleAndSong>();
            QaComments = new HashSet<QaComments>();
            SeasonAndSong = new HashSet<SeasonAndSong>();
            WardrobeAndSong = new HashSet<WardrobeAndSong>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public long GenreId { get; set; }
        public long ArtistId { get; set; }
        public long LabelId { get; set; }
        public long GroupId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public long ReadinessId { get; set; }
        public long? Size { get; set; }
        public int Channels { get; set; }
        public int SamplingSize { get; set; }
        public int Duration { get; set; }
        public int SamplingFrequency { get; set; }
        public string Name { get; set; }
        public long? AlbumId { get; set; }
        public long UploaderUserId { get; set; }
        public long[] Tags { get; set; }
        public string FilesInfo { get; set; }
        public int SortOrder { get; set; }
        public bool ParentalExplicit { get; set; }
        public long? MoodId { get; set; }
        public string ExternalPartnerId { get; set; }

        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Group Group { get; set; }
        public virtual Label Label { get; set; }
        public virtual Mood Mood { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual ICollection<AccountTransactionAndSong> AccountTransactionAndSong { get; set; }
        public virtual ICollection<BodyAnimationAndSong> BodyAnimationAndSong { get; set; }
        public virtual ICollection<BundleAndSong> BundleAndSong { get; set; }
        public virtual ICollection<DeviceTypeAndSong> DeviceTypeAndSong { get; set; }
        public virtual ICollection<GroupAndSong> GroupAndSong { get; set; }
        public virtual ICollection<MusicController> MusicController { get; set; }
        public virtual ICollection<PriceruleAndSong> PriceruleAndSong { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
        public virtual ICollection<SeasonAndSong> SeasonAndSong { get; set; }
        public virtual ICollection<WardrobeAndSong> WardrobeAndSong { get; set; }
    }
}