// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class Tag
    {
        public Tag()
        {
            TagPairsTag1Navigation = new HashSet<TagPairs>();
            TagPairsTag2Navigation = new HashSet<TagPairs>();
        }

        public long Id { get; set; }
        public long CategoryId { get; set; }
        public int SortOrder { get; set; }
        public string Name { get; set; }

        public virtual TagCategory Category { get; set; }
        public virtual ICollection<TagPairs> TagPairsTag1Navigation { get; set; }
        public virtual ICollection<TagPairs> TagPairsTag2Navigation { get; set; }
    }
}