// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class UmaAdjustment
    {
        public UmaAdjustment()
        {
            WardrobeSubCategoryAndUmaAdjustment = new HashSet<WardrobeSubCategoryAndUmaAdjustment>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public string Key { get; set; }
        public int SortOrder { get; set; }

        public virtual ICollection<WardrobeSubCategoryAndUmaAdjustment> WardrobeSubCategoryAndUmaAdjustment { get; set; }
    }
}