// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class UmaAssetFile
    {
        public UmaAssetFile()
        {
            UmaAssetFileAndUnityAssetType = new HashSet<UmaAssetFileAndUnityAssetType>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long UmaAssetId { get; set; }

        public virtual UmaAsset UmaAsset { get; set; }
        public virtual ICollection<UmaAssetFileAndUnityAssetType> UmaAssetFileAndUnityAssetType { get; set; }
    }
}