// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class UmaAssetFileAndUnityAssetType
    {
        public long UmaAssetFileId { get; set; }
        public long UnityAssetTypeId { get; set; }

        public virtual UmaAssetFile UmaAssetFile { get; set; }
        public virtual UnityAssetType UnityAssetType { get; set; }
    }
}