// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class UmaSharedColor
    {
        public UmaSharedColor()
        {
            WardrobeSubCategory = new HashSet<WardrobeSubCategory>();
            OutfitAndUmaSharedColor = new HashSet<OutfitAndUmaSharedColor>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public int[] Colors { get; set; }

        public virtual ICollection<WardrobeSubCategory> WardrobeSubCategory { get; set; }
        public virtual ICollection<OutfitAndUmaSharedColor> OutfitAndUmaSharedColor { get; set; }
    }
}