// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class VfxPositionGroup
    {
        public VfxPositionGroup()
        {
            VfxPositionGroupAndVfxSpawnPosition = new HashSet<VfxPositionGroupAndVfxSpawnPosition>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long VfxTypeId { get; set; }
        public long SetLocationId { get; set; }

        public virtual SetLocation SetLocation { get; set; }
        public virtual VfxType VfxType { get; set; }
        public virtual ICollection<VfxPositionGroupAndVfxSpawnPosition> VfxPositionGroupAndVfxSpawnPosition { get; set; }
    }
}