// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class VfxSpawnPosition
    {
        public VfxSpawnPosition()
        {
            VfxPositionGroupAndVfxSpawnPosition = new HashSet<VfxPositionGroupAndVfxSpawnPosition>();
        }

        public long Id { get; set; }
        public Guid UnityGuid { get; set; }
        public long SetLocationBundleId { get; set; }
        public string Name { get; set; }

        public virtual SetLocationBundle SetLocationBundle { get; set; }
        public virtual ICollection<VfxPositionGroupAndVfxSpawnPosition> VfxPositionGroupAndVfxSpawnPosition { get; set; }
    }
}