// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class VfxType
    {
        public VfxType()
        {
            SetLocation = new HashSet<SetLocation>();
            Vfx = new HashSet<Vfx>();
            VfxPositionGroup = new HashSet<VfxPositionGroup>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SetLocation> SetLocation { get; set; }
        public virtual ICollection<Vfx> Vfx { get; set; }
        public virtual ICollection<VfxPositionGroup> VfxPositionGroup { get; set; }
    }
}