// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class VfxWorldSize
    {
        public VfxWorldSize()
        {
            Vfx = new HashSet<Vfx>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Vfx> Vfx { get; set; }
    }
}