// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class VoiceFilter
    {
        public VoiceFilter()
        {
            AccountTransactionAndVoiceFilter = new HashSet<AccountTransactionAndVoiceFilter>();
            BundleAndVoiceFilter = new HashSet<BundleAndVoiceFilter>();
            CharacterControllerFaceVoice = new HashSet<CharacterControllerFaceVoice>();
            DeviceTypeAndVoiceFilter = new HashSet<DeviceTypeAndVoiceFilter>();
            GroupAndVoiceFilter = new HashSet<GroupAndVoiceFilter>();
            PriceruleAndVoiceFilter = new HashSet<PriceruleAndVoiceFilter>();
            QaComments = new HashSet<QaComments>();
            SeasonAndVoiceFilter = new HashSet<SeasonAndVoiceFilter>();
            WardrobeAndVoiceFilter = new HashSet<WardrobeAndVoiceFilter>();
        }

        public long Id { get; set; }
        public long? AssetStoreInfoId { get; set; }
        public int? Volume { get; set; }
        public int? Pitch { get; set; }
        public int? SendLevel { get; set; }
        public int? WetMixLevel { get; set; }
        public int? EffectParameters { get; set; }
        public long VoiceFilterCategoryId { get; set; }
        public long GroupId { get; set; }
        public long ReadinessId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }
        public string Name { get; set; }
        public long UploaderUserId { get; set; }
        public long[] Tags { get; set; }
        public string FilesInfo { get; set; }
        public int SortOrder { get; set; }
        public string DisplayName { get; set; }

        public virtual AssetStoreInfo AssetStoreInfo { get; set; }
        public virtual Group Group { get; set; }
        public virtual Readiness Readiness { get; set; }
        public virtual User UploaderUser { get; set; }
        public virtual VoiceFilterCategory VoiceFilterCategory { get; set; }
        public virtual ICollection<AccountTransactionAndVoiceFilter> AccountTransactionAndVoiceFilter { get; set; }
        public virtual ICollection<BundleAndVoiceFilter> BundleAndVoiceFilter { get; set; }
        public virtual ICollection<CharacterControllerFaceVoice> CharacterControllerFaceVoice { get; set; }
        public virtual ICollection<DeviceTypeAndVoiceFilter> DeviceTypeAndVoiceFilter { get; set; }
        public virtual ICollection<GroupAndVoiceFilter> GroupAndVoiceFilter { get; set; }
        public virtual ICollection<PriceruleAndVoiceFilter> PriceruleAndVoiceFilter { get; set; }
        public virtual ICollection<QaComments> QaComments { get; set; }
        public virtual ICollection<SeasonAndVoiceFilter> SeasonAndVoiceFilter { get; set; }
        public virtual ICollection<WardrobeAndVoiceFilter> WardrobeAndVoiceFilter { get; set; }
    }
}