// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeAndSong
    {
        public long WardrobeId { get; set; }
        public long SongId { get; set; }

        public virtual Song Song { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}