// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeAndCameraFilter
    {
        public long WardrobeId { get; set; }
        public long CameraFilterId { get; set; }

        public virtual CameraFilter CameraFilter { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}