// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeCollection
    {
        public WardrobeCollection()
        {
            Wardrobe = new HashSet<Wardrobe>();
            WardrobeCollectionAndBodyAnimationCategory = new HashSet<WardrobeCollectionAndBodyAnimationCategory>();
            WardrobeCollectionAndCameraFilterCategory = new HashSet<WardrobeCollectionAndCameraFilterCategory>();
            WardrobeCollectionAndGenre = new HashSet<WardrobeCollectionAndGenre>();
            WardrobeCollectionAndPropCategory = new HashSet<WardrobeCollectionAndPropCategory>();
            WardrobeCollectionAndScoreCategory = new HashSet<WardrobeCollectionAndScoreCategory>();
            WardrobeCollectionAndSetLocationCategory = new HashSet<WardrobeCollectionAndSetLocationCategory>();
            WardrobeCollectionAndSetLocationMood = new HashSet<WardrobeCollectionAndSetLocationMood>();
            WardrobeCollectionAndSfxCategory = new HashSet<WardrobeCollectionAndSfxCategory>();
            WardrobeCollectionAndVfxCategory = new HashSet<WardrobeCollectionAndVfxCategory>();
        }

        public long Id { get; set; }
        public long? BrandId { get; set; }
        public string Name { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual ICollection<Wardrobe> Wardrobe { get; set; }
        public virtual ICollection<WardrobeCollectionAndBodyAnimationCategory> WardrobeCollectionAndBodyAnimationCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndCameraFilterCategory> WardrobeCollectionAndCameraFilterCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndGenre> WardrobeCollectionAndGenre { get; set; }
        public virtual ICollection<WardrobeCollectionAndPropCategory> WardrobeCollectionAndPropCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndScoreCategory> WardrobeCollectionAndScoreCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndSetLocationCategory> WardrobeCollectionAndSetLocationCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndSetLocationMood> WardrobeCollectionAndSetLocationMood { get; set; }
        public virtual ICollection<WardrobeCollectionAndSfxCategory> WardrobeCollectionAndSfxCategory { get; set; }
        public virtual ICollection<WardrobeCollectionAndVfxCategory> WardrobeCollectionAndVfxCategory { get; set; }
    }
}