// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeSubCategory
    {
        public WardrobeSubCategory()
        {
            WardrobeAndWardrobeSubCategory = new HashSet<WardrobeAndWardrobeSubCategory>();
            WardrobeSubCategoryAndUmaAdjustment = new HashSet<WardrobeSubCategoryAndUmaAdjustment>();
        }

        public long Id { get; set; }
        public long WardrobeCategoryId { get; set; }
        public string Name { get; set; }
        public long? UmaSharedColorId { get; set; }
        public int SortOrder { get; set; }

        public virtual UmaSharedColor UmaSharedColor { get; set; }
        public virtual WardrobeCategory WardrobeCategory { get; set; }
        public virtual ICollection<WardrobeAndWardrobeSubCategory> WardrobeAndWardrobeSubCategory { get; set; }
        public virtual ICollection<WardrobeSubCategoryAndUmaAdjustment> WardrobeSubCategoryAndUmaAdjustment { get; set; }
    }
}