// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeStyleAndVfxCategory
    {
        public long WardrobeStyleId { get; set; }
        public long VfxCategoryId { get; set; }
        public int WardrobeStyleSortKey { get; set; }
        public int VfxCategorySortKey { get; set; }

        public virtual VfxCategory VfxCategory { get; set; }
        public virtual WardrobeStyle WardrobeStyle { get; set; }
    }
}