// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeStyleAndSfxCategory
    {
        public long WardrobeStyleId { get; set; }
        public long SfxCategoryId { get; set; }
        public int WardrobeStyleSortKey { get; set; }
        public int SfxCategorySortKey { get; set; }

        public virtual SfxCategory SfxCategory { get; set; }
        public virtual WardrobeStyle WardrobeStyle { get; set; }
    }
}