// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeAndScore
    {
        public long WardrobeId { get; set; }
        public long ScoreId { get; set; }

        public virtual Score Score { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}