// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeAndSetLocation
    {
        public long WardrobeId { get; set; }
        public long SetLocationId { get; set; }

        public virtual SetLocation SetLocation { get; set; }
        public virtual Wardrobe Wardrobe { get; set; }
    }
}