// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Bridge.Models.AsseManager
{
    public partial class WardrobeCollectionAndSetLocationMood
    {
        public long WardrobeCollectionId { get; set; }
        public long SetLocationMoodId { get; set; }
        public int WardrobeCollectionSortKey { get; set; }
        public int SetLocationMoodSortKey { get; set; }

        public virtual SetLocationMood SetLocationMood { get; set; }
        public virtual WardrobeCollection WardrobeCollection { get; set; }
    }
}